import { Ionicons } from "@expo/vector-icons";
import { router, type Href } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, RefreshControl, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";

import { AppStatusBar } from "@/components/ui/AppStatusBar";
import { EmptyState, ErrorState } from "@/components/ui/StateViews";
import { AppLayout, AppRadius } from "@/constants/layout";
import { DashboardSpacing as Spacing, type ThemeColors } from "@/constants/theme";
import { useAppToast } from "@/hooks/useAppToast";
import { deleteBrandThunk, fetchBrandsThunk } from "@/middleware/product/product.thunk";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { useThemeColors } from "@/theme/ThemeProvider";
import type { Brand } from "@/types/product";

export default function BrandsScreen() {
  const Colors = useThemeColors(); const styles = useMemo(() => createStyles(Colors), [Colors]);
  const dispatch = useAppDispatch(); const toast = useAppToast(); const insets = useSafeAreaInsets(); const state = useAppSelector((root) => root.product); const [query, setQuery] = useState("");
  useEffect(() => { void dispatch(fetchBrandsThunk(undefined)); }, [dispatch]);
  const brands = useMemo(() => state.brands.filter((brand) => brand.name.toLowerCase().includes(query.trim().toLowerCase())), [query, state.brands]);
  const remove = (brand: Brand) => Alert.alert("Delete Brand", `Delete "${brand.name}"? Products using it may need reassignment.`, [{ style:"cancel", text:"Cancel" }, { style:"destructive", text:"Delete", onPress:async()=>{ const action=await dispatch(deleteBrandThunk(brand.id)); if(deleteBrandThunk.rejected.match(action)) { Alert.alert("Unable to delete brand",action.payload?.message??"Please try again."); return; } toast.showSuccess("Brand deleted successfully."); } }]);
  return <SafeAreaView edges={["top"]} style={styles.safeArea}><AppStatusBar /><FlatList contentContainerStyle={styles.content} data={brands} keyExtractor={(item)=>item.id} refreshControl={<RefreshControl refreshing={state.brandsRefreshing} onRefresh={()=>void dispatch(fetchBrandsThunk({refresh:true}))} colors={[Colors.primary]} />} ListHeaderComponent={<View><View style={styles.header}><TouchableOpacity onPress={()=>router.canGoBack()?router.back():router.replace("/stock" as Href)} style={styles.iconButton}><Ionicons name="arrow-back" size={19} color={Colors.primary}/></TouchableOpacity><Text style={styles.title}>Brands</Text><View style={styles.spacer}/></View><View style={styles.search}><Ionicons name="search-outline" size={19} color={Colors.text2}/><TextInput onChangeText={setQuery} placeholder="Search brands" placeholderTextColor={Colors.placeholder} style={styles.searchInput} value={query}/></View><Text style={styles.count}>{brands.length} brand{brands.length===1?"":"s"}</Text></View>} ListEmptyComponent={state.brandsLoading?<View style={styles.loading}><ActivityIndicator size="large" color={Colors.primary}/></View>:state.brandError?<ErrorState message={state.brandError} onRetry={()=>void dispatch(fetchBrandsThunk({refresh:true}))} />:<EmptyState accent="indigo" description="Create a brand to organize your product catalog." icon="ribbon-outline" title="No brands found" />} ListFooterComponent={<View style={{paddingBottom:insets.bottom+16,paddingTop:Spacing.lg}}><TouchableOpacity onPress={()=>router.push("/stock/brands/new" as Href)} style={styles.addButton}><Ionicons name="add-circle-outline" size={19} color="#FFFFFF"/><Text style={styles.addText}>Add Brand</Text></TouchableOpacity></View>} renderItem={({item})=><TouchableOpacity activeOpacity={0.84} onPress={()=>router.push(`/stock/brands/${item.id}/edit` as Href)} style={styles.card}><View style={styles.brandIcon}><Ionicons name="ribbon-outline" size={20} color={Colors.primaryDark}/></View><View style={styles.copy}><View style={styles.nameRow}><Text numberOfLines={1} style={styles.brandName}>{item.name}</Text><Text style={[styles.status,!item.isActive&&styles.inactive]}>{item.isActive?"Active":"Inactive"}</Text></View><Text numberOfLines={1} style={styles.description}>{item.description??`${item.productCount} product${item.productCount===1?"":"s"}`}</Text></View><TouchableOpacity disabled={state.deletingBrandIds.includes(item.id)} hitSlop={8} onPress={(event)=>{event.stopPropagation();remove(item);}} style={styles.delete}>{state.deletingBrandIds.includes(item.id)?<ActivityIndicator color={Colors.error}/>:<Ionicons name="trash-outline" size={18} color={Colors.error}/>}</TouchableOpacity></TouchableOpacity>} /></SafeAreaView>;
}

const createStyles = (Colors: ThemeColors) => StyleSheet.create({safeArea:{backgroundColor:Colors.bg,flex:1},content:{padding:Spacing.lg},header:{alignItems:"center",flexDirection:"row",justifyContent:"space-between",marginBottom:Spacing.lg},iconButton:{alignItems:"center",backgroundColor:Colors.card,borderColor:Colors.border,borderRadius:AppRadius.control,borderWidth:1,height:AppLayout.headerActionSize,justifyContent:"center",width:AppLayout.headerActionSize},spacer:{width:AppLayout.headerActionSize},title:{color:Colors.heading,fontSize:24,fontWeight:"800"},search:{alignItems:"center",backgroundColor:Colors.card,borderColor:Colors.border,borderRadius:AppRadius.search,borderWidth:1,flexDirection:"row",gap:Spacing.sm,minHeight:52,paddingHorizontal:Spacing.md},searchInput:{color:Colors.heading,flex:1,fontSize:15,minHeight:50},count:{color:Colors.text2,fontSize:12,marginVertical:Spacing.md},card:{alignItems:"center",backgroundColor:Colors.card,borderColor:Colors.border,borderRadius:AppRadius.card,borderWidth:1,flexDirection:"row",marginBottom:Spacing.sm,padding:Spacing.md},brandIcon:{alignItems:"center",backgroundColor:Colors.bg2,borderRadius:AppRadius.control,height:44,justifyContent:"center",width:44},copy:{flex:1,marginLeft:Spacing.md,minWidth:0},nameRow:{alignItems:"center",flexDirection:"row",gap:Spacing.sm},brandName:{color:Colors.heading,flex:1,fontSize:15,fontWeight:"800"},status:{color:Colors.success,fontSize:10,fontWeight:"800"},inactive:{color:Colors.error},description:{color:Colors.text2,fontSize:12,marginTop:5},delete:{alignItems:"center",height:38,justifyContent:"center",marginLeft:Spacing.sm,width:34},empty:{alignItems:"center",padding:Spacing.xxl},emptyTitle:{color:Colors.heading,fontSize:18,fontWeight:"800",marginTop:Spacing.md},emptyText:{color:Colors.text2,fontSize:13,lineHeight:19,marginTop:Spacing.sm,textAlign:"center"},retry:{backgroundColor:Colors.primaryDark,borderRadius:AppRadius.pill,marginTop:Spacing.lg,paddingHorizontal:22,paddingVertical:11},retryText:{color:"#FFFFFF",fontWeight:"800"},loading:{alignItems:"center",padding:60},addButton:{alignItems:"center",backgroundColor:Colors.primaryDark,borderRadius:AppRadius.pill,flexDirection:"row",gap:Spacing.sm,justifyContent:"center",minHeight:54},addText:{color:"#FFFFFF",fontSize:14,fontWeight:"800"}});
