export interface BusinessType {
  slug: string
  name: string
  category: 'beauty' | 'wellness' | 'fitness'
  headline: string
  subheadline: string
  heroImage: string
  intro: string
  bullets: string[]
  aiInsight: string
  cta: string
  ctaSecondary: string
}

export const businessTypes: BusinessType[] = [
  // ── BEAUTY ──────────────────────────────────────────────────────────────
  {
    slug: 'salon',
    name: 'Salon',
    category: 'beauty',
    headline: 'Run Your Salon Smarter. Powered by AI.',
    subheadline: 'SalonOx brings together appointments, staff, clients, and payments into one intelligent platform — so you focus on the chair, not the chaos.',
heroImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&q=80',
    intro: 'SalonOx connects every part of your salon into a single smart system. When a client books online, their appointment lands instantly on your stylist\'s calendar. Your AI assistant handles reminders, follow-ups, and even suggests rebooking windows based on visit history.',
    bullets: [
      'AI-powered calendar fills your slots and reduces no-shows automatically.',
      'Every visit, service, and preference saved in one place.',
      'Accept UPI, card, or cash — with GST-ready invoices generated instantly.',
      'Assign services, track performance, and manage shifts with ease.',
      'Automated, personalized reminders sent directly to clients.',
    ],
    aiInsight: 'SalonOx\'s AI learns your busiest hours, top services, and most loyal clients — then helps you make smarter decisions every day. From predicting no-shows to suggesting the right promotions, your salon gets more intelligent over time.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See It in Action',
  },
  {
    slug: 'barber',
    name: 'Barber',
    category: 'beauty',
    headline: 'The Modern Barber Shop Deserves Modern Software.',
    subheadline: 'SalonOx gives barbers a fast, no-fuss system to manage bookings, walk-ins, and payments — with AI handling the busywork behind the scenes.',
heroImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1600&q=80',
    intro: 'Clients book a slot online or walk in — SalonOx queues them automatically. Barbers see their day at a glance: who\'s next, what service, how long. Payments are collected in seconds.',
    bullets: [
      'Manage online bookings and walk-ins without confusion or double entries.',
      'One tap to close a sale — cash, UPI, or card.',
      'Know who your top earner is and reward them.',
      'Keep regulars coming back with automated reward tracking.',
      'AI sends reminders and flags clients likely to cancel.',
    ],
    aiInsight: 'SalonOx\'s AI analyzes your booking patterns and tells you exactly when to run promotions, which services to upsell, and which clients are at risk of leaving — before they do.',
    cta: 'Get Started Free',
    ctaSecondary: 'Watch Demo',
  },
  {
    slug: 'brow-lash',
    name: 'Brow & Lash',
    category: 'beauty',
    headline: 'Precision Services Deserve Precise Management.',
    subheadline: 'SalonOx is built for brow and lash studios that need exact scheduling, detailed client notes, and smart follow-ups — all in one place.',
heroImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1600&q=80',
    intro: 'Each brow or lash service has its own duration, pricing, and prep notes. SalonOx lets you set up your service menu in detail, so when a client books, the right time block is reserved for the right technician.',
    bullets: [
      'Set exact durations per service — no guesswork.',
      'Track lash type, brow shape, allergies, and preferences per client.',
      'AI sends rebooking prompts at the perfect time.',
      'A branded page your clients can book from 24/7.',
      'Assign services to specific technicians only.',
    ],
    aiInsight: 'SalonOx uses AI to predict when a client is due for their next appointment and sends a personalized WhatsApp message — before they even think to call.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'See Features',
  },
  {
    slug: 'nail',
    name: 'Nail',
    category: 'beauty',
    headline: 'Beautiful Nails, Beautiful Business.',
    subheadline: 'SalonOx helps nail studios stay fully booked, reduce chaos at the front desk, and grow a loyal client base — with AI working quietly in the background.',
heroImage: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1600&q=80',
    intro: 'Clients browse your service menu, pick their nail artist, and book a slot — all without a phone call. SalonOx syncs everything in real time.',
    bullets: [
      'Clients choose their favourite nail technician.',
      'Reduce no-shows by requiring upfront payment.',
      'Track gel, polish, and supplies with automatic low-stock alerts.',
      'Reward repeat clients with AI-managed point systems.',
      'AI triggers review requests after every completed appointment.',
    ],
    aiInsight: 'SalonOx\'s AI identifies your highest-revenue services and clients, then helps you create targeted promotions that bring the right people back at the right time.',
    cta: 'Book a Demo',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'hair-removal',
    name: 'Hair Removal',
    category: 'beauty',
    headline: 'Manage Every Session. Grow Every Client.',
    subheadline: 'SalonOx is purpose-built for hair removal clinics that need accurate scheduling, session tracking, and intelligent client communication.',
heroImage: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1600&q=80',
    intro: 'Hair removal treatments require multiple sessions on specific timelines. SalonOx tracks every client\'s session count, interval, and treatment area — and the AI schedules their next appointment automatically.',
    bullets: [
      'Monitor each client\'s full treatment journey.',
      'AI prompts clients at the right interval for their next session.',
      'Digitally store client forms and patch test results.',
      'Assign and balance sessions across technicians.',
      'AI predicts upcoming revenue based on active treatment plans.',
    ],
    aiInsight: 'SalonOx\'s AI maps out the full treatment calendar for every client — so nothing slips through the cracks and retention stays high.',
    cta: 'Start Free Trial',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'makeup',
    name: 'Makeup',
    category: 'beauty',
    headline: 'From Bridal to Editorial — Manage Every Booking Effortlessly.',
    subheadline: 'SalonOx gives makeup artists and studios a smart booking system with client profiles, portfolio notes, and AI-powered scheduling.',
heroImage: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1600&q=80',
    intro: 'Clients book makeup appointments with full service details — occasion, look, duration, and artist preference. SalonOx stores their skin type, allergies, and past looks in their profile.',
    bullets: [
      'Categorize by bridal, event, shoot, editorial, etc.',
      'Save reference photos and notes per client.',
      'Secure advance payment for high-value bookings.',
      'Distribute bookings across artists based on availability.',
      'Automated booking confirmations and prep instructions.',
    ],
    aiInsight: 'During peak seasons, SalonOx\'s AI optimises your artist roster to maximise bookings without overbooking — so every client gets the attention they deserve.',
    cta: 'Get Started Free',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'tanning',
    name: 'Tanning',
    category: 'beauty',
    headline: 'Keep Your Beds Full and Your Business Glowing.',
    subheadline: 'SalonOx automates tanning studio scheduling, membership tracking, and client communication — powered by AI that works around the clock.',
heroImage: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=1600&q=80',
    intro: 'Clients book a tanning session online, select their bed type, and pay upfront. SalonOx tracks session credits, active memberships, and preferred beds per client.',
    bullets: [
      'Manage prepaid sessions and packages per client.',
      'Clients choose their preferred tanning unit.',
      'Sell and track monthly tanning memberships easily.',
      'AI fills slow periods with smart discount campaigns.',
      'In-studio payments done in seconds via UPI or card.',
    ],
    aiInsight: 'SalonOx analyses your occupancy in real time and uses AI to send targeted offers to clients who haven\'t visited recently — keeping your beds consistently booked.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'Book Demo',
  },
  {
    slug: 'tattoo',
    name: 'Tattoo',
    category: 'beauty',
    headline: 'Serious Art Deserves Serious Management.',
    subheadline: 'SalonOx helps tattoo studios manage consultations, multi-session bookings, deposits, and artist schedules — with AI reducing admin and increasing focus on craft.',
heroImage: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=1600&q=80',
    intro: 'Clients submit a booking request with their design brief and placement details. SalonOx assigns the right artist based on specialisation and availability. Deposits are collected upfront.',
    bullets: [
      'Manage the full journey from inquiry to completed piece.',
      'Route clients to artists based on style specialty.',
      'Collect and manage payments across multiple sessions.',
      'AI sends automated aftercare and check-in messages.',
      'Store consent forms digitally — no more paper files.',
    ],
    aiInsight: 'SalonOx\'s AI tracks each tattoo project\'s status, flags overdue sessions, and prompts clients automatically — so no project ever gets lost in the calendar.',
    cta: 'Book a Demo',
    ctaSecondary: 'Start Free',
  },

  // ── WELLNESS ─────────────────────────────────────────────────────────────
  {
    slug: 'spa',
    name: 'Spa',
    category: 'wellness',
    headline: 'Deliver Tranquility. Run on Intelligence.',
    subheadline: 'SalonOx helps spas create seamless guest experiences — from first booking to final checkout — with AI-powered scheduling, loyalty, and personalised communication.',
heroImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&q=80',
    intro: 'Guests discover your spa through your branded online booking page, select their treatment and therapist, and book in minutes. SalonOx prepares your team with full client details before arrival.',
    bullets: [
      'Guests return to the same therapist every time.',
      'Schedule rooms alongside staff to avoid conflicts.',
      'Create and sell multi-treatment spa packages easily.',
      'Recurring revenue through monthly wellness memberships.',
      'AI crafts individualised messages for every guest.',
    ],
    aiInsight: 'SalonOx\'s AI builds a wellness profile for every guest — tracking treatments, preferences, and visit frequency — so every touchpoint feels personal, not automated.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See Features',
  },
  {
    slug: 'aesthetic-clinic',
    name: 'Aesthetic Clinic',
    category: 'wellness',
    headline: 'Clinical Precision. Business Intelligence.',
    subheadline: 'SalonOx gives aesthetic clinics the tools to manage complex appointment workflows, treatment histories, and client communication — all backed by AI.',
heroImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1600&q=80',
    intro: 'Clients consult, book, and pay through one unified platform. Practitioners see full treatment histories before each appointment.',
    bullets: [
      'Map and track multi-step aesthetic journeys.',
      'Document client transformations securely.',
      'Manage complex multi-practitioner calendars.',
      'Compliant billing generated instantly after treatment.',
      'Store and retrieve client documents digitally.',
    ],
    aiInsight: 'SalonOx uses AI to analyse treatment cycles and alert practitioners when clients are due — increasing retention and treatment plan completion rates.',
    cta: 'Get Started Free',
    ctaSecondary: 'Book Demo',
  },
  {
    slug: 'med-spa',
    name: 'Med Spa',
    category: 'wellness',
    headline: 'Where Medical Expertise Meets Effortless Management.',
    subheadline: 'SalonOx is designed for med spas that need clinical-grade documentation, smart scheduling, and intelligent client retention tools in one platform.',
heroImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1600&q=80',
    intro: 'From consultation to checkout, every step is managed in SalonOx. Medical notes, treatment protocols, product usage, and payments all live in one record per client.',
    bullets: [
      'Keep detailed records for every client.',
      'Track injectables, serums, and consumables precisely.',
      'Control who sees and edits sensitive client records.',
      'AI schedules maintenance treatments in advance.',
      'Manage multiple med spa locations from one dashboard.',
    ],
    aiInsight: 'SalonOx\'s AI identifies drop-off patterns in your med spa and proactively re-engages clients before they switch to a competitor.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'massage',
    name: 'Massage',
    category: 'wellness',
    headline: 'More Healing. Less Hassle.',
    subheadline: 'SalonOx streamlines every aspect of your massage practice — from online booking and therapist scheduling to loyalty rewards and AI-powered client retention.',
heroImage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1600&q=80',
    intro: 'Clients book their preferred massage type, duration, and therapist online — anytime. SalonOx handles the confirmation, reminder, and follow-up automatically.',
    bullets: [
      'Eliminate double bookings with smart resource management.',
      'Save pressure level, focus areas, and health notes per client.',
      'Manage 5-session or 10-session package redemptions easily.',
      'AI sends 24-hour reminders to cut no-shows significantly.',
      'Reward frequent visitors with points and exclusive benefits.',
    ],
    aiInsight: 'SalonOx tracks visit frequency per client and uses AI to send a personal re-engagement message when someone is overdue — bringing them back before they forget.',
    cta: 'Book a Demo',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'chiropractor',
    name: 'Chiropractor',
    category: 'wellness',
    headline: 'Align Your Practice. Align Your Growth.',
    subheadline: 'SalonOx gives chiropractic clinics a smarter way to manage patient scheduling, treatment tracking, and automated follow-ups — powered by AI.',
heroImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1600&q=80',
    intro: 'New patients book a consultation online. SalonOx captures intake details before the appointment. After each session, the AI schedules the next based on the practitioner\'s recommended interval.',
    bullets: [
      'Gather patient details before they arrive.',
      'Map and automate multi-visit care plans.',
      'Full visibility into patient history at a glance.',
      'AI follows up with patients who miss appointments.',
      'Attach billing references to each patient file.',
    ],
    aiInsight: 'SalonOx\'s AI tracks patient visit adherence and sends targeted nudges when they fall off their treatment schedule — improving outcomes and clinic revenue simultaneously.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'nutritionist',
    name: 'Nutritionist',
    category: 'wellness',
    headline: 'Help Clients Reach Their Goals. Let AI Handle the Admin.',
    subheadline: 'SalonOx is built for nutrition professionals who want to manage consultations, track client progress, and stay connected — without the paperwork.',
heroImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1600&q=80',
    intro: 'Clients book a nutrition consultation online and fill out a health intake form. SalonOx stores their dietary history, goals, and session notes in one profile.',
    bullets: [
      'Track goals, dietary restrictions, weight history, and progress.',
      'Attach diet plans and documents to each client\'s record.',
      'AI checks in with clients between appointments.',
      'Clients book sessions without calling or emailing.',
      'Monitor income per client, package, and service type.',
    ],
    aiInsight: 'SalonOx uses AI to identify which clients are engaging less and sends personalised motivation messages to keep them on their wellness journey.',
    cta: 'Get Started Free',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'coaching',
    name: 'Coaching',
    category: 'wellness',
    headline: 'Scale Your Coaching Practice Without Scaling Your Workload.',
    subheadline: 'SalonOx gives life, wellness, and performance coaches a professional platform to manage sessions, track client progress, and grow their business with AI.',
heroImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1600&q=80',
    intro: 'Clients discover your coaching packages online, book a discovery call, and onboard through SalonOx. Session notes, goals, and action plans are tracked per client.',
    bullets: [
      'Sell and manage coaching programmes of any duration.',
      'Clients self-book within your available hours.',
      'Note milestones, goals, and wins per client.',
      'AI sends scheduled messages between sessions.',
      'Understand your growth at a glance.',
    ],
    aiInsight: 'SalonOx\'s AI analyses client engagement patterns and flags at-risk clients — giving you the insight to act before someone drops off.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'Book Demo',
  },
  {
    slug: 'physical-therapy',
    name: 'Physical Therapy',
    category: 'wellness',
    headline: 'Better Patient Outcomes. Better Practice Management.',
    subheadline: 'SalonOx helps physical therapy clinics manage complex treatment schedules, patient documentation, and automated follow-ups — intelligently.',
heroImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=1600&q=80',
    intro: 'Patients book their first evaluation online. SalonOx captures intake information and medical history. Therapists build a treatment plan inside the system.',
    bullets: [
      'Create and manage multi-week therapy programmes.',
      'Store assessments, progress notes, and exercise plans.',
      'Reduce no-shows with AI-triggered notifications.',
      'Complex schedules handled without confusion.',
      'Monitor patient progress from first session to discharge.',
    ],
    aiInsight: 'SalonOx uses AI to detect when patients are missing sessions and automatically sends re-engagement messages — improving adherence and clinic revenue.',
    cta: 'Book a Demo',
    ctaSecondary: 'Start Free',
  },

  // ── FITNESS ──────────────────────────────────────────────────────────────
  {
    slug: 'yoga',
    name: 'Yoga',
    category: 'fitness',
    headline: 'More Flow. Less Admin.',
    subheadline: 'SalonOx gives yoga studios the tools to manage class schedules, memberships, and student engagement — with AI that keeps your studio full and your students inspired.',
heroImage: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=1600&q=80',
    intro: 'Students browse your class schedule online, book their spot, and receive a confirmation instantly. SalonOx tracks attendance, credit usage, and membership status for every student.',
    bullets: [
      'Manage group classes and 1-on-1 sessions together.',
      'Sell and track class packs and memberships seamlessly.',
      'Auto-fill cancellations from the waitlist instantly.',
      'Assign classes, manage substitutions easily.',
      'Track who attends, how often, and what they prefer.',
    ],
    aiInsight: 'SalonOx\'s AI identifies students who haven\'t attended in a while and sends personalised re-engagement messages — keeping your community active and revenue consistent.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See Features',
  },
  {
    slug: 'gym',
    name: 'Gym',
    category: 'fitness',
    headline: 'Run a Smarter Gym with AI at Its Core.',
    subheadline: 'SalonOx gives gyms everything they need — from member management and class scheduling to AI-powered retention and multi-location control.',
heroImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1600&q=80',
    intro: 'Members sign up, choose their membership tier, and book classes or personal training sessions through SalonOx. Your team manages everything from one dashboard.',
    bullets: [
      'Handle monthly, quarterly, and annual plans effortlessly.',
      'Members book directly through your branded booking page.',
      'Monitor daily attendance with ease.',
      'AI reminds members before their membership expires.',
      'Manage all gym branches from one account.',
    ],
    aiInsight: 'SalonOx\'s AI scores each member\'s engagement level and automatically triggers personalised retention messages before they lapse — significantly reducing churn.',
    cta: 'Get Started Free',
    ctaSecondary: 'Book Demo',
  },
  {
    slug: 'personal-trainer',
    name: 'Personal Trainer',
    category: 'fitness',
    headline: 'Train More Clients. Do Less Admin.',
    subheadline: 'SalonOx is designed for personal trainers who want a professional client management system with smart scheduling, progress tracking, and automated communication.',
heroImage: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1600&q=80',
    intro: 'Clients book sessions through your personal booking link, pay upfront, and receive confirmation instantly. SalonOx tracks each client\'s session count, goals, and progress notes.',
    bullets: [
      'Your own branded link clients can book anytime.',
      'Track goals, measurements, and session notes.',
      'Manage block bookings and package redemptions.',
      'AI messages clients between sessions to maintain momentum.',
      'Track income per client, week, and service type.',
    ],
    aiInsight: 'SalonOx\'s AI analyses session frequency and client behaviour to suggest the optimal time to offer a programme upgrade — growing your income without the awkward upsell conversation.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'martial-arts',
    name: 'Martial Arts',
    category: 'fitness',
    headline: 'Discipline in Your Studio. Intelligence in Your Software.',
    subheadline: 'SalonOx gives martial arts academies a structured platform to manage class schedules, memberships, belt progress, and student retention — all powered by AI.',
heroImage: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=1600&q=80',
    intro: 'Students register online and choose their class level and schedule. SalonOx tracks attendance, belt progression, and renewal dates.',
    bullets: [
      'Organise beginner, intermediate, and advanced classes separately.',
      'Record each student\'s progression path.',
      'AI triggers renewal reminders before expiry.',
      'Send updates and schedules directly via WhatsApp.',
      'Assign and manage instructors across classes.',
    ],
    aiInsight: 'SalonOx uses AI to track attendance streaks and flag students who are losing consistency — so instructors can reach out before a dropout happens.',
    cta: 'Book a Demo',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'pilates',
    name: 'Pilates',
    category: 'fitness',
    headline: 'Precision Movement. Precision Management.',
    subheadline: 'SalonOx helps Pilates studios manage reformer bookings, private sessions, memberships, and client progress — with AI ensuring your studio always runs at its best.',
heroImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1600&q=80',
    intro: 'Clients book a reformer spot or private session online in real time. SalonOx manages equipment allocation, instructor assignment, and waitlists.',
    bullets: [
      'Assign reformers or mats per session automatically.',
      'Note technique improvements and programme milestones.',
      'Manage memberships and class packs through one seamless system.',
      'Fill cancellations instantly with AI-managed waitlists.',
      'AI identifies at-risk clients and re-engages them proactively.',
    ],
    aiInsight: 'SalonOx\'s AI predicts which clients are likely to reduce their frequency and triggers personalised outreach — before your studio feels the revenue impact.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'cross-training',
    name: 'Cross Training',
    category: 'fitness',
    headline: 'Push Limits in the Box. Not in Your Inbox.',
    subheadline: 'SalonOx gives CrossFit and cross-training boxes a complete management system — class scheduling, member tracking, performance notes, and AI-powered retention.',
heroImage: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=1600&q=80',
    intro: 'Athletes book their WOD class online, and SalonOx tracks attendance, performance notes, and membership status. Coaches have full visibility into their class roster.',
    bullets: [
      'Publish weekly schedules athletes can book from.',
      'Track benchmarks, PRs, and progress over time.',
      'Handle drop-ins, monthly memberships, and class packs.',
      'Designate coaches per class with clear ownership.',
      'AI triggers celebration messages for milestones and PRs.',
    ],
    aiInsight: 'SalonOx\'s AI creates an engagement score for each athlete and helps coaches focus retention efforts exactly where they\'re needed most.',
    cta: 'Get Started Free',
    ctaSecondary: 'Book Demo',
  },
  {
    slug: 'cycling',
    name: 'Cycling',
    category: 'fitness',
    headline: 'Full Speed Ahead — For Your Studio and Your Members.',
    subheadline: 'SalonOx powers indoor cycling studios with smart class management, bike-specific bookings, and AI-driven member engagement that keeps attendance high.',
heroImage: 'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=1600&q=80',
    intro: 'Members book their preferred bike spot in a class and receive an instant confirmation. SalonOx manages class capacity, instructor schedules, and membership credits.',
    bullets: [
      'Members claim their favourite bike in every class.',
      'Never overbook a session again.',
      'Manage multiple instructors across class types.',
      'Fuel competition and community with leaderboards.',
      'AI prompts members to book their next session immediately after class.',
    ],
    aiInsight: 'SalonOx uses AI to analyse riding frequency and proactively reach members who are slipping in attendance — with personalised messages that bring them back.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'dance-studio',
    name: 'Dance Studio',
    category: 'fitness',
    headline: 'Let Your Students Dance. Let SalonOx Handle the Rest.',
    subheadline: 'SalonOx is built for dance studios that need structured class management, recital scheduling, student tracking, and AI-powered communication — all in one place.',
heroImage: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=1600&q=80',
    intro: 'Students or parents book classes online by dance style, level, and instructor. SalonOx manages attendance, fees, and recital preparation schedules.',
    bullets: [
      'Organise ballet, contemporary, hip-hop, and more.',
      'Monitor progress and advancement per student.',
      'Automated WhatsApp updates for schedules and events.',
      'Know who\'s paid and who\'s outstanding at a glance.',
      'Plan performances alongside regular classes.',
    ],
    aiInsight: 'SalonOx\'s AI monitors enrolment trends by style and time slot — helping studio owners make data-driven decisions about class offerings and pricing.',
    cta: 'Book a Demo',
    ctaSecondary: 'Start Free',
  },
]

export const beautyTypes  = businessTypes.filter(b => b.category === 'beauty')
export const wellnessTypes = businessTypes.filter(b => b.category === 'wellness')
export const fitnessTypes  = businessTypes.filter(b => b.category === 'fitness')