export interface Feature {
  slug: string
  name: string
  group: string
  headline: string
  subheadline: string
  heroImage: string
  intro: string
  bullets: string[]
  aiInsight: string
  cta: string
  ctaSecondary: string
}

export const features: Feature[] = [
  {
    slug: 'scheduler',
    name: 'Scheduler',
    group: 'Run Your Business',
    headline: 'Your Entire Day, Organised by AI.',
    subheadline: 'SalonOx\'s AI-powered scheduler gives you a real-time view of every appointment, every staff member, and every resource — so nothing gets missed and nothing overlaps.',
heroImage: 'https://images.unsplash.com/photo-1758556549027-879615701c61?q=80',
    intro: 'The SalonOx Scheduler is your business\'s command centre. Appointments are displayed in day, week, or month view. Staff members appear as columns, and bookings slot in automatically based on availability, service duration, and room assignment.',
    bullets: [
      'Switch between day, week, and month views instantly.',
      'Drag and drop to reschedule without cancelling and rebooking.',
      'See everyone\'s day side by side for perfect coordination.',
      'Block time for breaks, training, or prep in one click.',
      'Smart AI recommendations to reduce gaps and increase utilisation.',
    ],
    aiInsight: 'SalonOx\'s AI monitors your scheduler in real time — identifying underbooked slots and automatically triggering promotions or outreach to fill them.',
    cta: 'See It in Action',
    ctaSecondary: 'Start Free Trial',
  },
  {
    slug: 'staff-shifts',
    name: 'Staff & Shifts',
    group: 'Run Your Business',
    headline: 'The Right Person. The Right Place. Every Time.',
    subheadline: 'SalonOx\'s Staff & Shifts module gives you complete control over your team\'s schedule — with AI ensuring optimal coverage based on your busiest hours.',
heroImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&q=80',
    intro: 'Add your staff, assign their services and working hours, and set their shift pattern. SalonOx builds the schedule automatically. Managers can view, edit, and publish shifts in minutes.',
    bullets: [
      'Create weekly or repeating shift patterns with ease.',
      'Staff only appear for services they\'re qualified for.',
      'Auto-send shift details directly to team members via WhatsApp.',
      'Log and manage time off in the same system.',
      'Track revenue, bookings, and utilisation per team member.',
    ],
    aiInsight: 'SalonOx uses AI to compare booking demand with shift coverage — alerting you when you\'re understaffed during peak periods before it impacts your clients.',
    cta: 'Start Free Trial',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'payroll',
    name: 'Payroll',
    group: 'Run Your Business',
    headline: 'Pay Your Team Right. Every Time. On Time.',
    subheadline: 'SalonOx\'s payroll system calculates commissions, wages, and bonuses automatically — so you close every pay run in minutes, not hours.',
heroImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1600&q=80',
    intro: 'Set up your team\'s pay structure — hourly, salary, or commission-based. SalonOx tracks hours worked, services performed, and products sold throughout the pay period.',
    bullets: [
      'Support for flat salary, hourly wages, and service commissions.',
      'No spreadsheets — SalonOx computes everything automatically.',
      'Detailed view of every staff member\'s earnings breakdown.',
      'Reward high performers with escalating commission rates.',
      'Download payroll summaries for your accountant or payroll software.',
    ],
    aiInsight: 'SalonOx\'s AI detects anomalies in payroll data — like sudden drops in commission or unusual hour patterns — and flags them before you approve the pay run.',
    cta: 'Get Started Free',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'roles-permissions',
    name: 'Roles & Permissions',
    group: 'Run Your Business',
    headline: 'Give Your Team Access. Keep Your Business Secure.',
    subheadline: 'SalonOx\'s Roles & Permissions system lets you define exactly what each team member can see, do, and change — protecting your data without slowing down your team.',
heroImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1600&q=80',
    intro: 'Create custom roles — Owner, Manager, Receptionist, Therapist — and assign granular permissions to each. Staff only see what they need.',
    bullets: [
      'Build roles that match your exact business structure.',
      'Control permissions down to individual features and data types.',
      'Different permissions for different branches.',
      'Every action is logged so you always know who changed what.',
      'New staff get the right access from day one.',
    ],
    aiInsight: 'SalonOx\'s AI monitors access patterns and alerts managers when unusual behaviour is detected — adding an intelligent layer of security to your business.',
    cta: 'Try SalonOx Free',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'reports-analytics',
    name: 'Reports & Analytics',
    group: 'Run Your Business',
    headline: 'Data That Drives Decisions. Not Just Numbers.',
    subheadline: 'SalonOx turns your business data into clear, actionable insights — powered by AI that surfaces what matters most, so you always know where to focus.',
heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80',
    intro: 'SalonOx tracks every transaction, appointment, client visit, and staff action. The Reports module turns this into visual dashboards covering revenue, services, staff performance, client behaviour, and inventory.',
    bullets: [
      'Daily, weekly, and monthly income at a glance.',
      'Know which services are growing and which are declining.',
      'Track each team member\'s bookings, revenue, and utilisation.',
      'Understand visit frequency, retention, and lifetime value.',
      'Plain-language AI summaries of what the data is telling you.',
    ],
    aiInsight: 'SalonOx\'s AI doesn\'t just report the past — it predicts the future. From forecasting next month\'s revenue to identifying clients at risk of leaving, your reports think ahead.',
    cta: 'See a Sample Report',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'online-booking',
    name: 'Online Booking',
    group: 'Grow Your Business',
    headline: 'Bookings While You Sleep. Revenue While You Work.',
    subheadline: 'SalonOx gives you a powerful online booking system that works 24/7 — letting clients book, pay, and confirm without any involvement from your team.',
heroImage: 'https://plus.unsplash.com/premium_photo-1664303914535-8dfcec4bb09e?q=80',
    intro: 'Your branded SalonOx booking page goes live instantly. Clients browse your services, choose their preferred staff, pick a time slot, and confirm their booking — with payment collected upfront if you choose.',
    bullets: [
      'Accept appointments around the clock — 24/7.',
      'Branded to your business with your services and pricing.',
      'Clients book with their favourite team member.',
      'Reduce no-shows with upfront payment requirements.',
      'Every online booking appears in your calendar immediately.',
    ],
    aiInsight: 'SalonOx\'s AI analyses your online booking patterns and recommends the best times to promote specific services — helping you fill strategic gaps with zero manual effort.',
    cta: 'Launch Your Booking Page',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'reserve-with-google',
    name: 'Reserve with Google',
    group: 'Grow Your Business',
    headline: 'Let Clients Book Right from Google Search.',
    subheadline: 'SalonOx integrates with Reserve with Google — so when someone searches for your business, they can book an appointment instantly without ever leaving the search page.',
heroImage: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=1600&q=80',
    intro: 'Once connected, a "Book" button appears directly on your Google Business Profile. When a client taps it, they\'re taken through a smooth booking flow — selecting service, staff, and time — all powered by SalonOx in the background.',
    bullets: [
      'Clients book from Google without downloading an app.',
      'Reach people searching for exactly what you offer.',
      'No manual updates — everything stays in sync automatically.',
      'Businesses with booking buttons rank higher in local searches.',
      'Show up looking polished right where clients find you.',
    ],
    aiInsight: 'SalonOx uses AI to track which Google bookings convert into repeat clients — helping you understand the true value of your search presence.',
    cta: 'Activate Reserve with Google',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'loyalty-program',
    name: 'Loyalty Program',
    group: 'Grow Your Business',
    headline: 'Turn First-Time Clients into Lifelong Fans.',
    subheadline: 'SalonOx\'s AI-powered loyalty programme rewards your clients automatically — making every visit more valuable and every client more likely to return.',
heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1600&q=80',
    intro: 'Every time a client books and pays, they earn loyalty points based on rules you define. Points accumulate and unlock rewards — discounts, free services, or exclusive offers.',
    bullets: [
      'No stamps, no cards — fully digital and seamless.',
      'Set your own point values, thresholds, and reward types.',
      'Clients can always see their current points balance.',
      'AI messages clients when they reach a new reward level.',
      'See how loyalty members compare to non-members in spend.',
    ],
    aiInsight: 'SalonOx\'s AI identifies clients approaching reward milestones and sends timely messages to encourage one more visit — naturally increasing booking frequency without discounting.',
    cta: 'Set Up Loyalty Today',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'inventory',
    name: 'Inventory',
    group: 'Grow Your Business',
    headline: 'Never Run Out. Never Overstock.',
    subheadline: 'SalonOx\'s AI-powered inventory system tracks every product in real time — alerting you before you run low and helping you order smarter every time.',
heroImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&q=80',
    intro: 'Add your products — retail and professional — and set minimum stock levels. SalonOx tracks usage automatically as products are consumed in services or sold to clients.',
    bullets: [
      'Always know exactly what\'s on your shelves.',
      'Get notified before you run out — not after.',
      'Understand what\'s being used in services vs. sold at the counter.',
      'Store supplier details and reorder directly from SalonOx.',
      'Perform regular audits digitally with no paperwork.',
    ],
    aiInsight: 'SalonOx\'s AI forecasts your reorder needs based on historical usage — suggesting quantities and timing so you never over-invest in stock or run short during a busy week.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'multi-location',
    name: 'Multi-location',
    group: 'Grow Your Business',
    headline: 'One Business. Many Locations. One Dashboard.',
    subheadline: 'SalonOx gives multi-location businesses a centralised command centre — with AI giving you unified visibility across all your branches in real time.',
heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80',
    intro: 'Add each location to your SalonOx account and manage them all from one login. Each branch has its own staff, calendar, inventory, and client database — but you see everything from the top.',
    bullets: [
      'View all locations\' revenue, bookings, and performance at once.',
      'Each location operates independently with its own settings.',
      'Manage team members who work across branches.',
      'Pull reports for a single location or the entire business.',
      'Clients can book any branch through the same booking page.',
    ],
    aiInsight: 'SalonOx\'s AI benchmarks your locations against each other and identifies underperforming branches early — giving you the insights to act before small gaps become big problems.',
    cta: 'Go Multi-Location',
    ctaSecondary: 'Contact Sales',
  },
  {
    slug: 'billing-invoices',
    name: 'Billing & Invoices',
    group: 'Simplify Payments',
    headline: 'Professional Invoices. Zero Effort.',
    subheadline: 'SalonOx generates accurate, branded invoices automatically after every service — with full support for GST, split payments, and detailed line items.',
heroImage: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=1600&q=80',
    intro: 'The moment a service is completed or a product is sold, SalonOx generates a detailed invoice automatically. It calculates totals, applies taxes, and formats everything professionally.',
    bullets: [
      'Created instantly at checkout — no manual entry needed.',
      'Add your logo and business details for a polished look.',
      'Fully formatted for Indian tax compliance with GST.',
      'Every charge clearly itemised.',
      'Search and retrieve any past invoice in seconds.',
    ],
    aiInsight: 'SalonOx\'s AI monitors billing patterns and flags unusual discrepancies — like repeated manual overrides or unusually large discounts — keeping your revenue protected.',
    cta: 'See How Billing Works',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'upi-card-cash',
    name: 'UPI / Card / Cash',
    group: 'Simplify Payments',
    headline: 'Accept Any Payment. Anywhere. Instantly.',
    subheadline: 'SalonOx supports every payment method your clients prefer — UPI, card, or cash — with every transaction tracked automatically and reconciled in real time.',
heroImage: 'https://images.unsplash.com/photo-1642060735155-234ded24d86e?q=80',
    intro: 'At checkout, your team selects the payment method — UPI, card, or cash. SalonOx records the transaction immediately, updates the client\'s invoice, and adds it to your daily sales report.',
    bullets: [
      'Accept Google Pay, PhonePe, Paytm, and all major UPI apps.',
      'Process debit and credit cards seamlessly.',
      'Log cash payments with full visibility in your end-of-day report.',
      'Handle partial payments across multiple methods.',
      'Know your daily take in real time, not at closing.',
    ],
    aiInsight: 'SalonOx\'s AI tracks payment method trends across your client base — helping you understand preferences and optimise your checkout experience accordingly.',
    cta: 'Set Up Payments',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'ewallet',
    name: 'eWallet',
    group: 'Simplify Payments',
    headline: 'Load Once. Pay Always.',
    subheadline: 'SalonOx\'s eWallet feature lets clients preload credit and pay for services instantly — reducing friction at checkout and improving cash flow for your business.',
heroImage: 'https://plus.unsplash.com/premium_vector-1682310937065-2576a67d6c9c?q=80',
    intro: 'Clients top up their SalonOx eWallet online or at the front desk. When they visit, their service is deducted from their balance automatically — no fumbling for cash or cards.',
    bullets: [
      'Clients pay from their wallet with a single tap.',
      'Wallet top-ups bring money in before services are delivered.',
      'Clients are notified when their wallet is running low.',
      'Clients can add credit from anywhere, anytime.',
      'Every wallet deduction is logged and transparent.',
    ],
    aiInsight: 'SalonOx\'s AI identifies clients with low or zero wallet balances and triggers timely top-up prompts — keeping the wallet active and your revenue flowing.',
    cta: 'Enable eWallet',
    ctaSecondary: 'Learn More',
  },
  {
    slug: 'gst-billing',
    name: 'GST Billing',
    group: 'Simplify Payments',
    headline: 'GST-Ready Billing. Compliant by Default.',
    subheadline: 'SalonOx generates fully GST-compliant invoices automatically — with correct tax calculations, GSTIN fields, and export-ready reports that make filing easy.',
heroImage: 'https://plus.unsplash.com/premium_photo-1679923906285-386991e8d862?q=80',
    intro: 'Add your GSTIN and tax rates once. SalonOx applies the correct GST automatically to every service and product. Each invoice is formatted to Indian tax standards.',
    bullets: [
      'Correct tax applied to every transaction, every time.',
      'Business and client GSTIN fields included by default.',
      'Add HSN/SAC codes per service and product for full compliance.',
      'Export monthly tax summaries for GSTR filing in minutes.',
      'Handle different rates for services and products seamlessly.',
    ],
    aiInsight: 'SalonOx\'s AI monitors your tax data throughout the month and flags potential discrepancies before your filing date — helping you stay compliant without last-minute stress.',
    cta: 'Start Free Trial',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'client-management',
    name: 'Client Management',
    group: 'Elevate Client Experience',
    headline: 'Know Your Clients Better Than They Know Themselves.',
    subheadline: 'SalonOx builds a rich, intelligent profile for every client — tracking their history, preferences, spending, and loyalty — so every interaction feels personal and informed.',
heroImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1600&q=80',
    intro: 'Every client who books, visits, or pays through SalonOx gets a detailed profile automatically. It captures their visit history, favourite services, preferred staff, spend per visit, and loyalty points.',
    bullets: [
      'Complete history at a glance before every appointment.',
      'Know your highest-value clients and reward them accordingly.',
      'Add private notes about preferences, allergies, or special requirements.',
      'Bring your current client database into SalonOx easily.',
      'Filter clients by visit frequency, spend, service type, and more.',
    ],
    aiInsight: 'SalonOx\'s AI continuously analyses your client database, identifying churn risks, high-value segments, and re-engagement opportunities — so you always know who to focus on.',
    cta: 'See Client Profiles',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'loyalty-tiers',
    name: 'Loyalty Tiers',
    group: 'Elevate Client Experience',
    headline: 'The More They Visit, The More They Feel Like VIPs.',
    subheadline: 'SalonOx\'s tiered loyalty system automatically upgrades clients as they earn more points — creating a powerful incentive to keep coming back.',
heroImage: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1600&q=80',
    intro: 'Create loyalty tiers — Silver, Gold, Platinum, or any names you choose. Set the point thresholds for each tier and define the perks that come with them.',
    bullets: [
      'Build as many tiers as your programme needs.',
      'Clients advance through tiers automatically — no manual management.',
      'Offer different discounts, benefits, or access per tier.',
      'AI congratulates clients when they move up.',
      'See the revenue impact of each loyalty tier clearly.',
    ],
    aiInsight: 'SalonOx\'s AI identifies clients who are just a visit or two away from the next tier and sends a well-timed nudge — turning occasional visitors into loyal regulars.',
    cta: 'Build Your Tiers',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'whatsapp-reminders',
    name: 'WhatsApp Reminders',
    group: 'Elevate Client Experience',
    headline: 'Reach Your Clients Where They Already Are.',
    subheadline: 'SalonOx sends automated, personalised WhatsApp reminders that reduce no-shows, re-engage lapsed clients, and keep your calendar full — without lifting a finger.',
heroImage: 'https://images.unsplash.com/photo-1600859343194-a5fae9ef9f66?q=80',
    intro: 'Connect your WhatsApp Business number to SalonOx. Define your reminder rules — 24 hours before, 2 hours before, or post-visit follow-up. SalonOx handles every message automatically.',
    bullets: [
      'Reduce no-shows with automated pre-visit messages.',
      'Send thank-you messages and rebooking prompts automatically.',
      'Every message includes the client\'s name and appointment details.',
      'Clients can confirm, cancel, or reschedule directly in WhatsApp.',
      'Monitor open and response rates per message type.',
    ],
    aiInsight: 'SalonOx\'s AI identifies the optimal time to send reminders based on each client\'s past response behaviour — maximising open rates and minimising no-shows.',
    cta: 'Set Up WhatsApp Reminders',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'online-booking-page',
    name: 'Online Booking Page',
    group: 'Elevate Client Experience',
    headline: 'Your Business Is Open 24/7 — Online.',
    subheadline: 'SalonOx creates a beautiful, branded booking page for your business that lets clients discover, browse, and book your services at any hour — with zero effort from your team.',
heroImage: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=1600&q=80',
    intro: 'SalonOx generates your online booking page automatically the moment you set up your services and staff. Customise it with your logo, brand colours, and service descriptions.',
    bullets: [
      'Your booking page is ready from day one — no development needed.',
      'Custom logo, colours, and service descriptions.',
      'Looks and works perfectly on every device.',
      'Only shows slots that are actually available.',
      'One link you can put everywhere — bio, messages, ads.',
    ],
    aiInsight: 'SalonOx\'s AI tracks booking page performance — showing you which services get the most views, where traffic comes from, and where clients drop off — so you can continuously improve conversions.',
    cta: 'Launch Your Booking Page',
    ctaSecondary: 'See Demo',
  },
  {
    slug: 'whatsapp-marketing',
    name: 'WhatsApp Marketing',
    group: 'Build Your Brand',
    headline: 'The Most Powerful Marketing Channel — Now AI-Powered.',
    subheadline: 'SalonOx lets you run targeted WhatsApp marketing campaigns that reach the right clients with the right message at the right time — all managed by AI.',
heroImage: 'https://plus.unsplash.com/premium_photo-1684761949804-fd8eb9a5b6cc?q=80',
    intro: 'Build a campaign in SalonOx\'s marketing module. Choose your audience — all clients, specific segments, or loyalty tiers. Write your message or use an AI-generated template.',
    bullets: [
      'Target by service history, visit frequency, location, or tier.',
      'Generate high-converting campaign copy in seconds with AI.',
      'Plan and automate campaigns days or weeks in advance.',
      'Track every campaign\'s reach, response, and revenue impact.',
      'WhatsApp Business API integration ensures message compliance.',
    ],
    aiInsight: 'SalonOx\'s AI writes your campaign message, recommends the best audience segment, and suggests the optimal send time — so every campaign is strategically optimised from the start.',
    cta: 'Launch Your First Campaign',
    ctaSecondary: 'Start Free',
  },
  {
    slug: 'salonbot-ai',
    name: 'SalonBot (AI)',
    group: 'Build Your Brand',
    headline: 'Meet SalonBot — Your AI Business Assistant.',
    subheadline: 'SalonBot is SalonOx\'s intelligent AI assistant that answers client questions, handles bookings, and provides business insights — automatically, 24/7.',
heroImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1600&q=80',
    intro: 'SalonBot connects to your WhatsApp and online booking page. When a client messages asking about availability, services, or prices, SalonBot responds instantly with accurate information — and guides them to book.',
    bullets: [
      'SalonBot handles FAQs, availability, and bookings via WhatsApp.',
      'Never miss an enquiry — SalonBot is always on, 24/7.',
      'Ask SalonBot how your week went and get a clear answer.',
      'Daily recommendations on what to focus on and who to re-engage.',
      'When conversations need a human, SalonBot routes them to your team.',
    ],
    aiInsight: 'SalonBot is not just a chatbot — it\'s a continuously learning AI trained on your business data. The more you use SalonOx, the smarter SalonBot becomes — giving you increasingly precise guidance every week.',
    cta: 'Activate SalonBot',
    ctaSecondary: 'Learn More',
  },
]

export const featureGroups = [
  {
    label: 'Run Your Business',
    features: features.filter(f => f.group === 'Run Your Business'),
  },
  {
    label: 'Grow Your Business',
    features: features.filter(f => f.group === 'Grow Your Business'),
  },
  {
    label: 'Simplify Payments',
    features: features.filter(f => f.group === 'Simplify Payments'),
  },
  {
    label: 'Elevate Client Experience',
    features: features.filter(f => f.group === 'Elevate Client Experience'),
  },
  {
    label: 'Build Your Brand',
    features: features.filter(f => f.group === 'Build Your Brand'),
  },
]