import { useEffect, useMemo, useState } from "react";
import { Printer, Eye, Check2 } from "react-bootstrap-icons";
import { useAppDispatch, useAppSelector } from "../../../hooks/useAppRedux";
import { createSettingThunk, updateSettingThunk } from "../../../middleware/setting/setting.thunk";
import { useStatusOverlay } from "../../../hooks/useStatusOverlay";
import Dropdown from "../../../components/ui/Dropdown";
import {
  PRINT_SETTING_KEY,
  DEFAULT_PRINT_CONFIG,
  PAPER_SIZE_LABELS,
  findPrintSetting,
  getPrintConfig,
  resolvePaperProfile,
  type PaperSize,
  type PrintConfig,
} from "../utils/printSettings";
import { buildThermalDocument, buildPageCss } from "../../bookings/utils/printTemplates";
import "../styles/PrintSettingsPage.scss";

// Print Settings — paper size and margins for every printed bill in the app.
// Stored as one JSON row in salon_settings (key PRINT_CONFIG), which is
// already salon-scoped, so the setting is inherently per salon/branch with no
// extra plumbing.

const PAPER_OPTIONS: { id: PaperSize; name: string }[] = [
  { id: "thermal_58", name: `${PAPER_SIZE_LABELS.thermal_58} (receipt roll)` },
  { id: "thermal_80", name: `${PAPER_SIZE_LABELS.thermal_80} (receipt roll)` },
  { id: "a4", name: `${PAPER_SIZE_LABELS.a4} (full invoice)` },
  { id: "custom", name: PAPER_SIZE_LABELS.custom },
];

// Stand-in bill used for the preview and the test print. Deliberately fixed
// sample data — the preview has to be viewable before any real sale exists,
// and identical output every time makes it obvious whether a change to the
// margins actually did anything.
const SAMPLE = {
  salonName: "Your Salon",
  salonAddress: "12 High Street, Pune, Maharashtra",
  salonPhone: "+91 98765 43210",
  gstNumber: "27ABCDE1234F1Z5",
  invoiceNo: "INV-00042",
  dateTime: "14 Aug 2026, 6:30 PM",
  clientName: "Shubham Bagal",
  clientPhone: "98765 43210",
  staffName: "Ram",
  items: [
    { name: "Hair Cut", qty: 1, amount: "₹500.00", meta: "Ram" },
    { name: "Hair Colour — Global", qty: 1, amount: "₹2,000.00", meta: "Veer" },
    { name: "Shampoo 200ml", qty: 2, amount: "₹700.00", meta: "Product" },
  ],
  summary: [
    { label: "Subtotal", value: "₹3,200.00" },
    { label: "Bill Discount", value: "−₹200.00", muted: true },
    { label: "CGST (2.5%)", value: "₹75.00" },
    { label: "SGST (2.5%)", value: "₹75.00" },
  ],
  grandTotal: { label: "TOTAL", value: "₹3,150.00" },
  payments: [{ label: "Paid", value: "₹3,150.00" }],
};

export default function PrintSettingsPage() {
  const dispatch = useAppDispatch();
  const items = useAppSelector((s) => s.setting.items);
  const { showSuccess, showError, overlay } = useStatusOverlay();

  const [config, setConfig] = useState<PrintConfig>(DEFAULT_PRINT_CONFIG);
  const [savedConfig, setSavedConfig] = useState<PrintConfig>(DEFAULT_PRINT_CONFIG);
  const [settingId, setSettingId] = useState<string | number | null>(null);
  const [saving, setSaving] = useState(false);

  // Hydrate from the store once settings arrive. Also re-runs if they're
  // refetched, so the form never shows a value the server no longer has.
  useEffect(() => {
    const existing = findPrintSetting(items);
    setSettingId(existing?.id ?? null);
    const loaded = getPrintConfig(items);
    setConfig(loaded);
    setSavedConfig(loaded);
  }, [items]);

  const profile = useMemo(() => resolvePaperProfile(config), [config]);
  const isCustom = config.paper_size === "custom";
  const dirty = JSON.stringify(config) !== JSON.stringify(savedConfig);

  const patch = (p: Partial<PrintConfig>) => setConfig((c) => ({ ...c, ...p }));
  const num = (v: string) => (v === "" ? 0 : Number(v));

  // Custom width/height are the two values that can make a page unprintable,
  // so they're validated in the form as well as clamped in resolvePaperProfile.
  const widthError = isCustom && (config.custom_width_mm < 30 || config.custom_width_mm > 300)
    ? "Width must be between 30mm and 300mm" : null;
  const heightError = isCustom && config.custom_height_mm !== 0
    && (config.custom_height_mm < 30 || config.custom_height_mm > 2000)
    ? "Height must be 0 (continuous roll) or between 30mm and 2000mm" : null;
  const hasError = !!(widthError || heightError);

  const buildPreviewHtml = (withToolbar: boolean) =>
    profile.isThermal
      ? buildThermalDocument(profile, SAMPLE, { title: "Print preview", withToolbar })
      : // A4/wide preview: the real A4 invoice is generated by receipt.ts from a
        // live booking, which doesn't exist here — so the preview shows the page
        // geometry with the sample bill laid out in the same proportions. The
        // @page rule is the genuine one, so margins/size are accurate.
        `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Print preview</title>
         <style>
           body{font-family:'Segoe UI',Helvetica,Arial,sans-serif;background:#d1d5db;margin:0;color:#111827}
           .page{width:${profile.contentWidthMm}mm;min-height:${profile.heightMm > 0 ? profile.heightMm : 297}mm;
                 padding:${profile.margins.top}mm ${profile.margins.right}mm ${profile.margins.bottom}mm ${profile.margins.left}mm;
                 box-sizing:content-box;margin:12mm auto;background:#fff;box-shadow:0 4px 24px rgba(0,0,0,.18)}
           h1{font-size:20px;margin:0 0 4px}
           .meta{font-size:11px;color:#6b7280;line-height:1.7}
           table{width:100%;border-collapse:collapse;font-size:11.5px;margin-top:18px}
           th{background:#f9fafb;text-align:left;padding:8px 10px;border:1px solid #d1d5db;font-size:9.5px;text-transform:uppercase;letter-spacing:.4px}
           td{padding:8px 10px;border:1px solid #e5e7eb}
           .r{text-align:right}
           .tot{margin-top:14px;margin-left:auto;width:240px;border-collapse:collapse}
           .tot td{padding:6px 12px;border:1px solid #e5e7eb;font-size:12px}
           .grand td{font-weight:800;border-top:2px solid #111827}
           .foot{margin-top:26px;font-size:10.5px;color:#6b7280;border-top:1px solid #e5e7eb;padding-top:10px}
           ${withToolbar ? `.tb{position:fixed;top:0;left:0;right:0;height:44px;background:#111827;color:#fff;display:flex;align-items:center;justify-content:center;gap:8px;z-index:9;font-size:13px}
           .tb button{background:#2563eb;color:#fff;border:0;border-radius:6px;padding:7px 16px;font-weight:600;cursor:pointer}
           body{padding-top:56px}` : ""}
           @media print{.tb{display:none}body{background:#fff;padding-top:0}.page{margin:0;padding:0;box-shadow:none;width:auto;min-height:0}}
         </style>
         <style id="page-style">${buildPageCss(profile)}</style></head><body>
         ${withToolbar ? `<div class="tb"><span>Print preview</span><button onclick="window.print()">Print</button></div>` : ""}
         <div class="page">
           <h1>${SAMPLE.salonName}</h1>
           <div class="meta">${SAMPLE.salonAddress}<br/>Ph: ${SAMPLE.salonPhone} &nbsp;|&nbsp; GSTIN: ${SAMPLE.gstNumber}</div>
           <div class="meta" style="margin-top:10px"><strong>Invoice ${SAMPLE.invoiceNo}</strong> &nbsp;|&nbsp; ${SAMPLE.dateTime}<br/>Client: ${SAMPLE.clientName} (${SAMPLE.clientPhone})</div>
           <table><thead><tr><th>Item</th><th>Staff</th><th class="r">Qty</th><th class="r">Amount</th></tr></thead><tbody>
             ${SAMPLE.items.map((i) => `<tr><td>${i.name}</td><td>${i.meta ?? "—"}</td><td class="r">${i.qty}</td><td class="r">${i.amount}</td></tr>`).join("")}
           </tbody></table>
           <table class="tot"><tbody>
             ${SAMPLE.summary.map((s) => `<tr><td>${s.label}</td><td class="r">${s.value}</td></tr>`).join("")}
             <tr class="grand"><td>${SAMPLE.grandTotal.label}</td><td class="r">${SAMPLE.grandTotal.value}</td></tr>
           </tbody></table>
           <div class="foot">Thank you for your visit! &nbsp;|&nbsp; Powered by Salonox</div>
         </div></body></html>`;

  const openPreview = () => {
    const win = window.open("", "_blank", "width=720,height=880");
    if (!win) { showError("Please allow popups to see the print preview."); return; }
    win.document.write(buildPreviewHtml(true));
    win.document.close();
    win.focus();
  };

  // Test print goes through a hidden iframe and fires the print dialog
  // directly — the point is to confirm the real printer output before saving,
  // so it must not require the user to click Print inside a preview window.
  const testPrint = () => {
    const iframe = document.createElement("iframe");
    iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;";
    document.body.appendChild(iframe);
    const doc = iframe.contentWindow?.document;
    if (!doc) { iframe.remove(); showError("Couldn't open the print dialog."); return; }
    doc.open();
    doc.write(buildPreviewHtml(false));
    doc.close();
    const fire = () => {
      try { iframe.contentWindow?.focus(); iframe.contentWindow?.print(); } catch { /* no printer available */ }
      setTimeout(() => iframe.remove(), 60_000);
    };
    if (doc.readyState === "complete") setTimeout(fire, 200);
    else iframe.addEventListener("load", () => setTimeout(fire, 200));
  };

  const save = async () => {
    if (hasError) return;
    setSaving(true);
    const value = JSON.stringify(config);
    let ok = false;
    if (settingId) {
      const res = await dispatch(updateSettingThunk({ id: settingId, data: { key: PRINT_SETTING_KEY, value } }));
      ok = updateSettingThunk.fulfilled.match(res);
    } else {
      const res = await dispatch(createSettingThunk({
        key: PRINT_SETTING_KEY, value, description: "Printer / paper configuration",
      }));
      if (createSettingThunk.fulfilled.match(res)) { setSettingId(res.payload.id); ok = true; }
    }
    setSaving(false);
    if (ok) { setSavedConfig(config); showSuccess("Print settings saved"); }
    else showError("Couldn't save print settings");
  };

  return (
    <div className="prs-page">
      {overlay}

      <div className="prs-head">
        <div>
          <h1><Printer size={18} /> Print Settings</h1>
          <p>
            Choose the paper your printer uses. Every printed bill — Quick Sale, Calendar
            appointment, Invoice and Package/Membership sale — follows this setting.
          </p>
        </div>
      </div>

      <div className="prs-grid">
        <div className="prs-card">
          <h2>Paper</h2>

          <label className="prs-label">Paper size</label>
          <Dropdown
            className="prs-input"
            searchable={false}
            value={config.paper_size}
            options={PAPER_OPTIONS}
            onChange={(id) => patch({ paper_size: id as PaperSize })}
          />
          <p className="prs-hint">
            {profile.isThermal
              ? `Receipt layout — single column, ${profile.contentWidthMm}mm of printable width.`
              : "Full invoice layout — itemised table, totals block and footer notes."}
          </p>

          {isCustom && (
            <>
              <div className="prs-row">
                <div>
                  <label className="prs-label">Paper width (mm)</label>
                  <input
                    className={`prs-input${widthError ? " prs-input--err" : ""}`}
                    type="number" min={30} max={300}
                    value={config.custom_width_mm}
                    onChange={(e) => patch({ custom_width_mm: num(e.target.value) })}
                    onWheel={(e) => e.currentTarget.blur()}
                  />
                </div>
                <div>
                  <label className="prs-label">Paper height (mm)</label>
                  <input
                    className={`prs-input${heightError ? " prs-input--err" : ""}`}
                    type="number" min={0} max={2000}
                    value={config.custom_height_mm}
                    onChange={(e) => patch({ custom_height_mm: num(e.target.value) })}
                    onWheel={(e) => e.currentTarget.blur()}
                  />
                </div>
              </div>
              {widthError && <span className="prs-err">{widthError}</span>}
              {heightError && <span className="prs-err">{heightError}</span>}
              <p className="prs-hint">
                Set height to <strong>0</strong> for a continuous roll — the receipt then ends
                where the content ends instead of feeding blank paper to a fixed page length.
              </p>

              <h2 className="prs-sub">Margins (mm)</h2>
              <div className="prs-row prs-row--4">
                {([
                  ["margin_top_mm", "Top"],
                  ["margin_bottom_mm", "Bottom"],
                  ["margin_left_mm", "Left"],
                  ["margin_right_mm", "Right"],
                ] as const).map(([key, label]) => (
                  <div key={key}>
                    <label className="prs-label">{label}</label>
                    <input
                      className="prs-input"
                      type="number" min={0} max={50}
                      value={config[key]}
                      onChange={(e) => patch({ [key]: num(e.target.value) } as Partial<PrintConfig>)}
                      onWheel={(e) => e.currentTarget.blur()}
                    />
                  </div>
                ))}
              </div>
            </>
          )}

          <div className="prs-actions">
            <button className="prs-btn" onClick={openPreview}><Eye size={14} /> Preview</button>
            <button className="prs-btn" onClick={testPrint}><Printer size={14} /> Test print</button>
            <button className="prs-btn prs-btn--primary" onClick={save} disabled={saving || hasError || !dirty}>
              <Check2 size={15} /> {saving ? "Saving…" : dirty ? "Save changes" : "Saved"}
            </button>
          </div>
        </div>

        <div className="prs-card prs-card--summary">
          <h2>Resolved layout</h2>
          <dl className="prs-summary">
            <div><dt>Template</dt><dd>{profile.isThermal ? "Thermal receipt" : "A4 invoice"}</dd></div>
            <div><dt>Paper</dt><dd>{profile.widthMm}mm × {profile.heightMm > 0 ? `${profile.heightMm}mm` : "continuous"}</dd></div>
            <div><dt>Printable width</dt><dd>{profile.contentWidthMm}mm</dd></div>
            <div>
              <dt>Margins</dt>
              <dd>{profile.margins.top} / {profile.margins.right} / {profile.margins.bottom} / {profile.margins.left} mm</dd>
            </div>
            <div><dt>Font scale</dt><dd>{profile.fontScale}×</dd></div>
            <div><dt>Logo</dt><dd>{profile.logoPx}px</dd></div>
          </dl>
          <p className="prs-hint">
            Logo, font size, spacing, table width, totals and footer all scale from these
            figures — there's no separate layout to keep in sync per printer.
          </p>
        </div>
      </div>
    </div>
  );
}
