import { AppLayout, AppRadius } from "@/constants/layout";
import type { ThemeColors } from '@/constants/theme';
import { DashboardSpacing as Spacing } from "@/constants/theme";
import { StyleSheet } from 'react-native';

export const createAppointmentDetailsStyles = (Colors: ThemeColors) => StyleSheet.create({
  appointmentDetailsModal: {
    backgroundColor: Colors.appointmentSurface,
    elevation: 24,
    maxHeight: "82%",
    minHeight: "68%",
    shadowColor: Colors.shadow,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.26,
    shadowRadius: 20,
    width: "100%",
  },
  appointmentModalHeader: {
    alignItems: "flex-start",
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  appointmentModalHeading: { flex: 1, minWidth: 0 },
  appointmentModalTitle: { color: Colors.appointmentText, fontSize: 18, fontWeight: "900" },
  appointmentClientBand: {
    alignItems: "center",
    backgroundColor: Colors.appointmentAccentSoft,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  appointmentClientAvatar: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderRadius: 28,
    height: 56,
    justifyContent: "center",
    width: 56,
  },
  appointmentClientCopy: { flex: 1, minWidth: 0 },
  appointmentClientName: { color: Colors.appointmentText, fontSize: 20, fontWeight: "900", lineHeight: 25 },
  appointmentClientPhone: { color: Colors.appointmentTextSecondary, fontSize: 14, marginTop: 5 },
  appointmentStatusControl: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    maxWidth: 132,
    minHeight: 48,
    paddingHorizontal: 10,
  },
  appointmentStatusDot: { borderRadius: 5, height: 10, width: 10 },
  appointmentStatusLabel: { color: Colors.appointmentTextSecondary, flexShrink: 1, fontSize: 13, fontWeight: "700" },
  appointmentTabs: {
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  appointmentTabButton: {
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
    minHeight: 48,
  },
  appointmentTabActive: {
    borderBottomColor: Colors.appointmentAccent,
    borderBottomWidth: 3,
    color: Colors.appointmentAccent,
    fontSize: 18,
    fontWeight: "900",
    paddingBottom: 12,
  },
  appointmentTab: { color: Colors.appointmentText, fontSize: 18, fontWeight: "600", paddingBottom: 12 },
  appointmentModalContent: { flexGrow: 1, padding: 18 },
  appointmentServiceHeading: { color: Colors.appointmentText, fontSize: 18, fontWeight: "900", marginBottom: 16 },
  appointmentServiceCard: {
    borderColor: Colors.appointmentBorder,
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
  },
  appointmentServiceTop: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" },
  appointmentServiceName: { color: Colors.appointmentText, flex: 1, fontSize: 17, fontWeight: "900", paddingRight: 10 },
  appointmentServiceTime: { color: Colors.appointmentText, fontSize: 13 },
  appointmentServiceMeta: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  appointmentBookedBy: { color: Colors.appointmentTextSecondary, flex: 1, fontSize: 13 },
  appointmentWith: { color: Colors.appointmentTextSecondary, fontSize: 13 },
  appointmentServiceStatus: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 22 },
  appointmentServiceStatusText: { color: Colors.appointmentText, fontSize: 16, fontWeight: "700" },
  appointmentNotesHeading: {
    color: Colors.appointmentText,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 14,
  },
  appointmentNotesText: {
    color: Colors.appointmentText,
    fontSize: 15,
    lineHeight: 23,
  },
  appointmentNotesEmpty: {
    color: Colors.appointmentTextSecondary,
  },
  appointmentNotesButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: Colors.appointmentAccent,
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    marginTop: 22,
    minHeight: 44,
    paddingHorizontal: 16,
  },
  appointmentNotesButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  appointmentInvoiceButton: {
    alignItems: "center",
    backgroundColor: Colors.appointmentAccent,
    borderRadius: 28,
    flexDirection: "row",
    gap: 9,
    justifyContent: "center",
    margin: 18,
    minHeight: 54,
  },
  appointmentInvoiceDisabled: { opacity: 0.45 },
  appointmentInvoiceText: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  previewSheet: {
    backgroundColor: Colors.appointmentSurface,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    elevation: 20,
    paddingBottom: 12,
    paddingHorizontal: 18,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
  },
  previewHandle: {
    alignSelf: "center",
    backgroundColor: Colors.appointmentBorder,
    borderRadius: 3,
    height: 4,
    marginBottom: 12,
    marginTop: 9,
    width: 42,
  },
  previewHeader: {
    alignItems: "center",
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 48,
  },
  previewClose: {
    alignItems: "center",
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  previewTitle: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    marginLeft: 3,
  },
  previewStatusBadge: {
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  previewPaidBadge: {
    backgroundColor: "#DDF4D9",
  },
  previewUnpaidBadge: {
    backgroundColor: Colors.appointmentAccentSoft,
  },
  previewStatusText: {
    color: "#238A32",
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  previewUnpaidText: {
    color: Colors.appointmentAccentDark,
  },
  previewDetailRow: {
    alignItems: "center",
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 52,
    paddingHorizontal: 4,
    paddingVertical: 7,
  },
  previewDetailCopy: {
    flex: 1,
    minWidth: 0,
  },
  previewDetailPrimary: {
    color: Colors.appointmentText,
    fontSize: 13,
    fontWeight: "600",
  },
  previewDetailSecondary: {
    color: Colors.appointmentTextSecondary,
    fontSize: 11,
    marginTop: 3,
  },
  previewDetailTrailing: {
    color: Colors.appointmentText,
    fontSize: 13,
    fontWeight: "800",
  },
  previewDetailsButton: {
    alignItems: "center",
    backgroundColor: Colors.appointmentAccent,
    borderRadius: 6,
    justifyContent: "center",
    marginTop: 12,
    minHeight: 44,
  },
  previewDetailsButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "800",
  },
  appointmentCoreRow: {
    backgroundColor: Colors.appointmentSurface,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 0,
    paddingTop: 16,
  },
  appointmentCoreField: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 0,
  },
  previewBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.34)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  appointmentSearchDropdown: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    elevation: 6,
    left: 0,
    marginTop: 6,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    top: AppLayout.searchBarHeight,
    zIndex: 6,
  },
  appointmentSearchDropdownScroll: {
    maxHeight: 260,
  },
  appointmentSearchEmpty: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
  },
  appointmentSearchEmptyText: {
    color: Colors.text2,
    fontSize: 12,
    fontWeight: "700",
  },
  appointmentSearchRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: Spacing.sm,
  },
  appointmentSearchGroup: {
    position: "relative",
    zIndex: 5,
  },
  appointmentSearchGroupFlex: {
    flex: 1,
  },
  appointmentSearchItem: {
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
  },
  appointmentSearchItemMeta: {
    color: Colors.text2,
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  appointmentSearchItemTitle: {
    color: Colors.heading,
    fontSize: 13,
    fontWeight: "800",
  },
  appointmentHeaderCopy: {
    flex: 1,
    marginLeft: 4,
  },
  appointmentHeaderSubtitle: {
    color: Colors.appointmentTextSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 1,
  }
});
