import { AppLayout } from "@/constants/layout";
import type { ThemeColors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const createCalendarControlsStyles = (Colors: ThemeColors) => StyleSheet.create({
  calendarHeadingRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 14, paddingBottom: 10 },
  calendarHeading: { color: Colors.appointmentText, fontSize: 23, fontWeight: "700", letterSpacing: -0.5 },
  calendarViewButton: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderColor: Colors.appointmentBorder, borderRadius: 8, paddingHorizontal: 12, minHeight: 40 },
  dinggToolbar: {
    backgroundColor: Colors.appointmentSurface,
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    marginHorizontal: -AppLayout.contentHorizontalPadding,
    paddingBottom: 8,
    paddingHorizontal: 16,
  },
  dinggToolbarActions: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 52,
  },
  dinggTodayButton: {
    backgroundColor: Colors.appointmentSurfaceMuted,
    borderColor: Colors.appointmentDivider,
    borderWidth: 1,
    borderRadius: 8,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  dinggTodayText: {
    color: Colors.appointmentText,
    fontSize: 13,
    fontWeight: "700",
  },
  dinggToolbarIcons: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  dinggRangeControls: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 3,
    justifyContent: "center",
  },
  dinggRangeButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    minWidth: 108,
  },
  dinggRangeText: {
    color: Colors.appointmentText,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
    textAlign: "center",
  },
  calendarFilterRow: {
    alignItems: "center",
    borderTopColor: Colors.appointmentDivider,
    borderTopWidth: 0,
    flexDirection: "row",
    gap: 8,
    paddingRight: 4,
  },
  calendarStaffFilter: {
    borderTopWidth: 0,
    flex: 1,
    minWidth: 0,
  },
  dinggStylistSummary: {
    alignItems: "center",
    borderTopColor: Colors.appointmentDivider,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 10,
  },
  dinggStylistLabel: {
    color: Colors.appointmentText,
    fontSize: 13,
    fontWeight: "800",
  },
  dinggStylistValue: {
    color: Colors.appointmentTextSecondary,
    fontSize: 13,
    maxWidth: "65%",
  },
  dinggSearchField: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurfaceMuted,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.appointmentDivider,
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
    minHeight: 44,
    paddingHorizontal: 10,
  },
  dinggSearchInput: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 13,
    minHeight: 44,
  },
  dinggToolbarIcon: {
    borderWidth: 1,
    borderColor: Colors.appointmentDivider,
    borderRadius: 8,
    alignItems: "center",
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  dinggStaffRow: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 4,
  },
  dinggStaffChip: {
    borderColor: "transparent",
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 32,
    justifyContent: "center",
    paddingHorizontal: 13,
  },
  dinggStaffChipActive: {
    backgroundColor: Colors.appointmentAccent,
    borderColor: Colors.appointmentAccent,
  },
  dinggStaffText: {
    color: Colors.appointmentText,
    fontSize: 11,
    fontWeight: "600",
  },
  dinggStaffTextActive: {
    color: "#FFFFFF",
  },
  dinggLegend: {
    backgroundColor: "transparent",
    bottom: 0,
    flexGrow: 0,
    left: 0,
    position: "absolute",
    right: 0,
    zIndex: 10,
  },
  dinggLegendContent: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  dinggLegendPill: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderRadius: 22,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 42,
    minWidth: 88,
    paddingHorizontal: 16,
  },
  dinggLegendActive: {
    backgroundColor: Colors.appointmentAccent,
  },
  dinggLegendDot: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  dinggLegendText: {
    color: Colors.appointmentText,
    fontSize: 11,
    fontWeight: "600",
  },
  dinggLegendTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  dinggStaffHeader: {
    color: Colors.appointmentText,
    fontSize: 10,
    fontWeight: "800",
  }
});
