import { AppRadius } from "@/constants/layout";
import type { ThemeColors } from '@/constants/theme';
import { DashboardRadius as Radius, DashboardSpacing as Spacing } from "@/constants/theme";
import { StyleSheet } from 'react-native';

export const createServicePickerStyles = (Colors: ThemeColors) => StyleSheet.create({
  catalogAddButton: {
    alignItems: "center",
    backgroundColor: Colors.appointmentAccentSoft,
    borderRadius: 7,
    flexDirection: "row",
    gap: 6,
    minHeight: 46,
    minWidth: 92,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  catalogAddText: {
    color: Colors.appointmentText,
    fontSize: 14,
    fontWeight: "900",
  },
  catalogQuantityButton: {
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentAccent,
    borderWidth: 1,
  },
  catalogQuantityText: {
    color: Colors.appointmentText,
    fontSize: 14,
    fontWeight: "700",
    minWidth: 18,
    textAlign: "center",
  },
  servicePickerFooter: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderTopColor: Colors.appointmentDivider,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 88,
    paddingHorizontal: 30,
    paddingVertical: 10,
  },
  servicePickerCount: {
    color: Colors.appointmentText,
    flex: 0.7,
    fontSize: 16,
    fontWeight: "900",
  },
  servicePickerContinue: {
    alignItems: "center",
    backgroundColor: Colors.appointmentAccent,
    borderRadius: AppRadius.pill,
    flex: 1.3,
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    minHeight: 54,
  },
  servicePickerContinueText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  serviceDropdown: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    elevation: 6,
    left: 0,
    marginTop: 6,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    top: 76,
    zIndex: 5,
  },
  serviceDropdownScroll: {
    maxHeight: 360,
  },
  serviceDropdownState: {
    alignItems: "center",
    flexDirection: "row",
    gap: Spacing.sm,
    minHeight: 52,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
  },
  selectedServiceCard: {
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentDivider,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    minHeight: 64,
    padding: 10,
    position: "relative",
    width: "100%",
  },
  selectedServiceCardActive: {
    borderColor: Colors.border,
  },
  selectedServiceCopy: {
    flex: 1,
    minWidth: 0,
  },
  selectedServiceIcon: {
    alignItems: "center",
    backgroundColor: Colors.bg2,
    borderRadius: Radius.lg,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  selectedServiceMeta: {
    color: Colors.text2,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
  },
  selectedServiceName: {
    color: Colors.appointmentText,
    fontSize: 14,
    fontWeight: "900",
    paddingRight: 18,
  },
  selectedServicePrice: {
    color: Colors.appointmentAccent,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 6,
  },
  selectedServiceRow: {
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  serviceSearchGroup: {
    position: "relative",
    zIndex: 4,
  },
  serviceTotalDivider: {
    backgroundColor: Colors.border,
    width: 1,
  },
  serviceTotalItem: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: Spacing.md,
  },
  serviceBreakdownCard: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    marginTop: Spacing.sm,
    padding: Spacing.md,
  },
  serviceTotalsCard: {
    backgroundColor: Colors.infoBg,
    borderColor: Colors.border,
    borderWidth: 1,
    borderRadius: AppRadius.control,
    flexDirection: "row",
    gap: Spacing.md,
    marginTop: Spacing.md,
    padding: 10,
  },
  serviceOptionChip: {
    backgroundColor: Colors.bg,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    minWidth: 148,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
  },
  serviceOptionMeta: {
    color: Colors.text2,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 3,
  },
  serviceOptionMetaActive: {
    color: "rgba(255,255,255,0.82)",
  },
  serviceOptionCopy: {
    flex: 1,
    minWidth: 0,
  },
  serviceOptionName: {
    color: Colors.heading,
    fontSize: 13,
    fontWeight: "900",
  },
  serviceOptionNameActive: {
    color: "#FFFFFF",
  },
  serviceOptionNameMatch: {
    backgroundColor: Colors.successBg,
    color: Colors.primaryDark,
  },
  serviceOptionPrice: {
    color: Colors.primaryDark,
    fontSize: 13,
    fontWeight: "900",
  },
  serviceOptionPriceActive: {
    color: "#FFFFFF",
  },
  serviceOptionPriceMatch: {
    backgroundColor: Colors.successBg,
    borderRadius: Radius.sm,
    overflow: "hidden",
    paddingHorizontal: 4,
  },
  serviceOptionRow: {
    alignItems: "center",
    backgroundColor: Colors.card,
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: Spacing.md,
    minHeight: 62,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
  },
  serviceOptionRowActive: {
    backgroundColor: Colors.primary,
  },
  servicePickerSafeArea: {
    backgroundColor: Colors.appointmentBackground,
    flex: 1,
  },
  servicePickerHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 72,
    paddingHorizontal: 24,
  },
  servicePickerBack: {
    alignItems: "center",
    height: 40,
    justifyContent: "center",
    width: 34,
  },
  servicePickerTitle: {
    color: Colors.appointmentText,
    fontFamily: "serif",
    fontSize: 24,
    fontWeight: "700",
  },
  servicePickerBody: {
    flex: 1,
    paddingHorizontal: 24,
  },
  servicePickerLabel: {
    color: Colors.appointmentText,
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },
  servicePickerSelect: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 58,
    paddingHorizontal: 16,
  },
  servicePickerSelectText: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
  },
  servicePickerSelectPlaceholder: {
    color: Colors.appointmentPlaceholder,
  },
  servicePickerSearch: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 58,
    paddingHorizontal: 16,
  },
  servicePickerSearchInput: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 16,
    minHeight: 56,
  },
  serviceCategoryScroll: {
    flexGrow: 0,
    marginHorizontal: -24,
    marginTop: 20,
  },
  serviceCategoryRow: {
    flexDirection: "row",
    gap: 26,
    paddingHorizontal: 24,
  },
  serviceCategoryTab: {
    minHeight: 42,
  },
  serviceCategoryText: {
    color: Colors.appointmentTextSecondary,
    fontSize: 15,
    fontWeight: "600",
  },
  serviceCategoryTextActive: {
    color: Colors.appointmentAccent,
    fontWeight: "900",
  },
  serviceCategoryIndicator: {
    backgroundColor: Colors.appointmentAccent,
    height: 3,
    marginTop: 10,
    width: 24,
  },
  servicePickerState: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  servicePickerEmpty: {
    color: Colors.appointmentTextSecondary,
    fontSize: 14,
    paddingVertical: 48,
    textAlign: "center",
  },
  catalogServiceRow: {
    alignItems: "center",
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 98,
    paddingVertical: 14,
  },
  catalogServiceCopy: {
    flex: 1,
  },
  catalogServiceName: {
    color: Colors.appointmentText,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 21,
  },
  catalogServiceMeta: {
    color: Colors.appointmentAccent,
    fontSize: 14,
    fontWeight: "800",
    marginTop: 8,
  },
  catalogServiceDivider: {
    color: Colors.appointmentMuted,
  }
});
