import { AppLayout, AppRadius } from "@/constants/layout";
import type { ThemeColors } from '@/constants/theme';
import { DashboardSpacing as Spacing } from "@/constants/theme";
import { StyleSheet } from 'react-native';

export const createSharedStyles = (Colors: ThemeColors) => StyleSheet.create({
  actionButton: {
    alignItems: "center",
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minHeight: 74,
    justifyContent: "center",
  },
  actionButtonDanger: {
    backgroundColor: Colors.errorBg,
    borderColor: Colors.errorBorder,
  },
  actionButtonText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: "800",
  },
  actionButtonTextDanger: {
    color: Colors.error,
  },
  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: AppLayout.sectionGap,
  },
  amountText: {
    color: Colors.heading,
    fontSize: 14,
    fontWeight: "900",
  },
  twoColumn: {
    flexDirection: "row",
    gap: Spacing.md,
  },
  twoColumnItem: {
    flex: 1,
  },
  notesText: {
    color: Colors.heading,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    marginTop: Spacing.sm,
  },
  autocompleteAnchor: {
    overflow: "visible",
    position: "relative",
    zIndex: 50,
  },
  compactStatusField: {
    flex: 0.92,
    minWidth: 0,
  },
  compactSelectButton: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentBorder,
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: "row",
    gap: 3,
    minHeight: 48,
    paddingHorizontal: 8,
  },
  compactSelectText: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 11,
    fontWeight: "600",
  },
  mutedText: {
    color: Colors.text2,
    fontSize: 12,
    fontWeight: "700",
  },
  optionChip: {
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentBorder,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: Spacing.md,
    paddingVertical: 9,
  },
  optionChipActive: {
    backgroundColor: Colors.appointmentAccentSoft,
    borderColor: Colors.appointmentAccent,
  },
  optionChipText: {
    color: Colors.appointmentTextSecondary,
    fontSize: 12,
    fontWeight: "600",
  },
  optionChipTextActive: {
    color: Colors.appointmentAccentDark,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: Colors.primaryDark,
    borderRadius: AppRadius.pill,
    flexDirection: "row",
    gap: Spacing.sm,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: AppLayout.cardPadding,
  },
  primaryButtonCompact: {
    alignItems: "center",
    backgroundColor: Colors.primaryDark,
    borderRadius: AppRadius.pill,
    flex: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    justifyContent: "center",
    minHeight: 46,
  },
  primaryButtonSmall: {
    alignItems: "center",
    backgroundColor: Colors.primary,
    borderRadius: AppRadius.pill,
    justifyContent: "center",
    marginTop: Spacing.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 12,
  },
  primaryButtonSmallText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
  rawKey: {
    color: Colors.text2,
    fontSize: 12,
    fontWeight: "800",
    width: 130,
  },
  rawList: {
    marginTop: Spacing.md,
  },
  rawRow: {
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  rawValue: {
    color: Colors.heading,
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
  },
  readOnlyInput: {
    backgroundColor: Colors.bg2,
    color: Colors.text2,
  },
  removeServiceButton: {
    alignItems: "center",
    backgroundColor: Colors.errorBg,
    borderRadius: 12,
    height: 24,
    justifyContent: "center",
    position: "absolute",
    right: 8,
    top: 8,
    width: 24,
  },
  safeArea: {
    backgroundColor: Colors.appointmentBackground,
    flex: 1,
  },
  searchInput: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 14,
    minHeight: 48,
  },
  searchWrap: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentBorder,
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    minHeight: AppLayout.searchBarHeight,
    paddingHorizontal: AppLayout.searchBarPaddingX,
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: Colors.bg2,
    borderRadius: AppRadius.pill,
    flex: 1,
    justifyContent: "center",
    minHeight: 46,
  },
  secondaryButtonText: {
    color: Colors.heading,
    fontSize: 13,
    fontWeight: "900",
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: Spacing.md,
    marginTop: Spacing.sm,
  },
  sectionTitle: {
    color: Colors.heading,
    fontSize: 17,
    fontWeight: "900",
  },
  segment: {
    borderRadius: AppRadius.pill,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  segmentActive: {
    backgroundColor: Colors.primary,
  },
  segmented: {
    backgroundColor: Colors.bg2,
    borderRadius: AppRadius.pill,
    flexDirection: "row",
    padding: 3,
  },
  segmentText: {
    color: Colors.text2,
    fontSize: 11,
    fontWeight: "900",
  },
  segmentTextActive: {
    color: "#FFFFFF",
  },
  skeletonLine: {
    backgroundColor: Colors.bg2,
    borderRadius: AppRadius.pill,
    height: 14,
    marginTop: Spacing.sm,
    width: "80%",
  },
  skeletonLineShort: {
    width: "48%",
  },
  skeletonTitle: {
    backgroundColor: Colors.bg2,
    borderRadius: AppRadius.pill,
    height: 18,
    width: "55%",
  },
  snackbar: {
    alignItems: "center",
    backgroundColor: Colors.primaryDark,
    borderRadius: AppRadius.pill,
    bottom: 16,
    flexDirection: "row",
    gap: Spacing.sm,
    left: Spacing.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    position: "absolute",
    right: Spacing.lg,
  },
  snackbarError: {
    backgroundColor: Colors.error,
  },
  snackbarText: {
    color: "#FFFFFF",
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
  },
  stack: {
    gap: Spacing.md,
  },
  textInput: {
    backgroundColor: Colors.bg,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    color: Colors.heading,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: Spacing.md,
  },
  emptyAddServicesButton: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: Colors.appointmentSurface,
    borderColor: Colors.appointmentAccent,
    borderRadius: 28,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    marginVertical: 26,
    minHeight: 48,
    paddingHorizontal: 20,
  },
  emptyAddServicesIcon: {
    alignItems: "center",
    backgroundColor: Colors.appointmentAccent,
    borderRadius: 18,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  emptyAddServicesText: {
    color: Colors.appointmentAccent,
    fontSize: 16,
    fontWeight: "700",
  },
  stylistModalBackdrop: {
    backgroundColor: "rgba(0,0,0,0.48)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  stylistModalCard: {
    backgroundColor: Colors.appointmentSurface,
    borderRadius: 10,
    maxHeight: "64%",
    padding: 18,
  },
  stylistModalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  stylistModalTitle: {
    color: Colors.appointmentText,
    fontSize: 20,
    fontWeight: "900",
  },
  stylistOptionRow: {
    alignItems: "center",
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 58,
  },
  stylistOptionName: {
    color: Colors.appointmentText,
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
  },
  stylistAvailability: {
    color: Colors.appointmentAccent,
    fontSize: 12,
    fontWeight: "700",
  },
  card: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.card,
    borderWidth: 1,
    marginBottom: AppLayout.sectionGap,
    padding: AppLayout.cardPadding,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
    elevation: 2,
  },
  cardFooter: {
    alignItems: "center",
    borderTopColor: Colors.border,
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: Spacing.md,
    paddingTop: Spacing.md,
  },
  cardSubtitle: {
    color: Colors.text2,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 2,
  },
  cardTitle: {
    color: Colors.heading,
    fontSize: 16,
    fontWeight: "900",
  },
  cardTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: Spacing.md,
  },
  content: {
    paddingBottom: AppLayout.contentBottomPadding,
    paddingHorizontal: 24,
    paddingTop: Spacing.sm,
  },
  fixedContent: {
    flex: 1,
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: Colors.error,
    borderRadius: AppRadius.pill,
    flexDirection: "row",
    gap: Spacing.sm,
    justifyContent: "center",
    minHeight: 52,
    paddingHorizontal: AppLayout.cardPadding,
  },
  dangerButtonCompact: {
    alignItems: "center",
    backgroundColor: Colors.error,
    borderRadius: AppRadius.pill,
    flex: 1,
    justifyContent: "center",
    minHeight: 46,
  },
  detailHero: {
    alignItems: "center",
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.card,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.md,
    marginBottom: AppLayout.sectionGap,
    padding: AppLayout.cardPadding,
  },
  detailInvoiceRow: {
    alignItems: "center",
    backgroundColor: Colors.appointmentSurface,
    borderBottomColor: Colors.appointmentDivider,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    paddingBottom: 14,
  },
  detailInvoiceLabel: {
    color: Colors.appointmentTextSecondary,
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  detailInvoiceNumber: {
    color: Colors.appointmentText,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 4,
  },
  detailHeroCopy: {
    flex: 1,
  },
  detailHeroMeta: {
    color: Colors.text2,
    fontSize: 13,
    fontWeight: "600",
    marginTop: 3,
  },
  detailHeroTitle: {
    color: Colors.heading,
    fontSize: 18,
    fontWeight: "900",
  },
  detailLabel: {
    color: Colors.text2,
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
  },
  detailRow: {
    borderBottomColor: Colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: Spacing.md,
    paddingVertical: Spacing.md,
  },
  detailValue: {
    color: Colors.heading,
    flex: 1.4,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
  },
  disabledButton: {
    opacity: 0.68,
  },
  emptyInlineState: {
    alignItems: "center",
    backgroundColor: Colors.bg,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderStyle: "dashed",
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    padding: Spacing.md,
  },
  floatingDropdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "transparent",
  },
  floatingDropdownLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 999,
  },
  floatingSearchDropdown: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    elevation: 24,
    overflow: "hidden",
    position: "absolute",
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 28,
    zIndex: 1000,
  },
  flatListContent: {
    paddingBottom: AppLayout.contentBottomPadding,
    paddingHorizontal: AppLayout.contentHorizontalPadding,
  },
  flex: {
    flex: 1,
  },
  footerLoader: {
    padding: Spacing.lg,
  },
  formCard: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
    borderRadius: AppRadius.card,
    borderWidth: 1,
    marginBottom: AppLayout.sectionGap,
    padding: AppLayout.cardPadding,
    position: "relative",
  },
  formDismissOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  calculatedCard: {
    backgroundColor: Colors.bg,
    borderColor: Colors.border,
    borderRadius: AppRadius.control,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    marginBottom: Spacing.lg,
    padding: Spacing.md,
  },
  calculatedItem: {
    flex: 1,
    minWidth: 0,
  },
  existingClientToggle: {
    alignItems: "center",
    alignSelf: "flex-start",
    borderColor: Colors.border,
    borderRadius: AppRadius.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    minHeight: 38,
    paddingHorizontal: Spacing.md,
  },
  existingClientToggleActive: {
    backgroundColor: Colors.bg2,
    borderColor: Colors.primary,
  },
  existingClientToggleText: {
    color: Colors.text2,
    fontSize: 12,
    fontWeight: "900",
  },
  existingClientToggleTextActive: {
    color: Colors.primary,
  },
  headerRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    minHeight: 48,
  },
  headerTitle: {
    color: Colors.appointmentText,
    fontFamily: "serif",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 30,
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    height: AppLayout.headerActionSize,
    justifyContent: "center",
    width: AppLayout.headerActionSize,
  },
  iconButtonGhost: {
    height: AppLayout.headerActionSize,
    width: AppLayout.headerActionSize,
  },
  inlineAlert: {
    alignItems: "center",
    backgroundColor: Colors.errorBg,
    borderRadius: AppRadius.control,
    flexDirection: "row",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    padding: Spacing.md,
  },
  inlineAlertText: {
    color: Colors.error,
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
  },
  linkText: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: "900",
  },
  listHeader: {
    paddingTop: Spacing.sm,
  },
  metaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  metaPill: {
    alignItems: "center",
    backgroundColor: Colors.bg,
    borderRadius: AppRadius.pill,
    flexDirection: "row",
    gap: 5,
    maxWidth: "48%",
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  metaPillText: {
    color: Colors.text2,
    fontSize: 12,
    fontWeight: "700",
  }
});
