import type { useRedemptions } from "@/features/quickSale/hooks/useRedemptions";
import type { CartItem, QuickSaleClient } from "@/features/quickSale/types";
import type { BillTotals } from "@/features/quickSale/utils/calculations";
import type { ValidateCouponResult } from "@/types/coupon";
import type { CheckoutSaleSplitEntry, PosStaffMember, SalePaymentMethod } from "@/types/sales";

export type CheckoutStep = "review" | "charges" | "payment";
export type DiscountApplyTarget = "service" | "product" | "package" | "membership" | "entireBill";
export type ExtraChargeKey = "convenienceFee" | "otherCharges" | "serviceCharge";

export type CheckoutSheetProps = {
  appliedCoupon: ValidateCouponResult | null;
  consumableProductNames: Record<string, string>;
  couponCode: string;
  couponError: string | null;
  discountApplyTo: DiscountApplyTarget[];
  extraCharges: Record<ExtraChargeKey, string>;
  gstPreviewAmount: number;
  hasItems: boolean;
  includeGst: boolean;
  initialStep: CheckoutStep;
  initialStaffValidationAttempted?: boolean;
  isApplyingCoupon: boolean;
  isCheckingOut: boolean;
  isPricingLoading: boolean;
  isSaving: boolean;
  isSuccess: boolean;
  pricingError: string | null;
  items: CartItem[];
  onAddMore: () => void;
  onApplyCoupon: () => void;
  onAssignStaff: (lineId: string, staffId: string | null, staffName: string | null) => void;
  onChangeCouponCode: (value: string) => void;
  onChangeDiscountApplyTo: (targets: DiscountApplyTarget[]) => void;
  onChangeCustomer: () => void;
  onChangeExtraCharge: (key: ExtraChargeKey, value: string) => void;
  onChangeOverallDiscount: (value: string, type: "flat" | "percentage", percentage: number) => void;
  onChangeTip: (value: string) => void;
  onClose: () => void;
  onCompleteSale: (payment: {
    method: SalePaymentMethod;
    paidAmount: number;
    splitEntries?: CheckoutSaleSplitEntry[];
  }) => void;
  onRemoveCoupon: () => void;
  onRemoveItem: (lineId: string) => void;
  onRequireClientDetails?: () => void;
  onSavePending: () => void;
  onSetConsumableActualQty: (lineId: string, productId: string, actualQty: number) => void;
  onSetQuantity: (lineId: string, quantity: number) => void;
  onToggleIncludeGst: () => void;
  overallDiscountInput: string;
  overallDiscountPercent: number;
  overallDiscountType: "flat" | "percentage";
  productStockErrors: Record<string, string>;
  redemptions: ReturnType<typeof useRedemptions>;
  renderInline?: boolean;
  selectedClient: QuickSaleClient;
  staffOptions: PosStaffMember[];
  submitError: string | null;
  tipInput: string;
  totals: BillTotals;
  visible: boolean;
};
