export const REPORT = {
  APPOINTMENT_DETAIL: "/api/report/appointment-detail",
  CLIENT_RATING: "/api/report/client-rating",
  CLIENT_REVENUE: "/api/report/client-revenue",
  CUSTOMER_FREQUENCY: "/api/report/customer-frequency",
  CUSTOMER_SPEND: "/api/report/customer-spend",
  DAILY_SHEET: "/api/report/daily-sheet",
  E_WALLET: "/api/report/ewallet",
  GST: "/api/report/gst",
  LOST_CUSTOMERS: "/api/report/lost-customers",
  MEMBER_SALE: "/api/report/member-sale",
  OPEN_RATE: "/api/report/open-rate",
  PACKAGE_HISTORY: "/api/report/package-history",
  PACKAGE_SALE: "/api/report/package-sale",
  PAYMENT_COLLECTION: "/api/report/payment-collection",
  PRODUCT_INVENTORY: "/api/report/product-inventory",
  PRODUCT_INVENTORY_SALES: "/api/report/product-inventory-sales",
  PRODUCT_MARGIN: "/api/report/product-margin",
  PRODUCT_RETAIL: "/api/report/product-retail",
  REFERRAL: "/api/report/referral",
  REPLY_RATE: "/api/report/reply-rate",
  REWARD_POINTS: "/api/report/reward-points",
  SALES_SUMMARY: "/api/report/sales-summary",
  SALES_SUMMARY_DETAIL: (saleId: string) => `/api/report/sales-summary/${saleId}`,
  SERVICE_SALE: "/api/report/service-sale",
  SERVICE_FREQUENCY: "/api/report/service-frequency",
  STAFF_ITEM_SALES: "/api/report/staff-item-sales",
  STAFF_PERFORMANCE: "/api/report/staff-performance",
  STAFF_SALES: "/api/report/staff-sales",
  UPCOMING_APPOINTMENTS: "/api/report/upcoming-appointments",
  MEMBERSHIP_HISTORY: "/api/report/membership-history",
  WA_CAMPAIGN: "/api/report/wa-campaign",
} as const;
