export const SUPER_ADMIN = {
  LOGIN:          "/api/v1/super-admin/login",
  STATS:          "/api/v1/super-admin/stats",
  RECENT_LOGINS:     "/api/v1/super-admin/recent-logins",
  FREQUENT_LOGINS:   "/api/v1/super-admin/frequent-logins",
  USERS_NO_PLAN:          "/api/v1/super-admin/users-no-plan",
  SALON_PERMISSIONS_SEARCH: "/api/v1/super-admin/salon-permissions/search",
  SALON_PERMISSIONS_GET:    (id: string) => `/api/v1/super-admin/salon-permissions/${id}`,
  SALON_PERMISSIONS_PUT:    (id: string) => `/api/v1/super-admin/salon-permissions/${id}`,
  SALONS:        "/api/v1/super-admin/salons",
  SALON_STATUS:  (id: string) => `/api/v1/super-admin/salons/${id}/status`,
  SALON_ONBOARD: (id: string) => `/api/v1/super-admin/salons/${id}/onboarding`,
  SALON_IMPERSONATE: (id: string) => `/api/v1/super-admin/salons/${id}/impersonate`,
  PAYMENTS:      "/api/v1/super-admin/payments",
  USERS:         "/api/v1/super-admin/users",
  USER_STATUS:   (id: string) => `/api/v1/super-admin/users/${id}/status`,
  USER_ROLE:     (id: string) => `/api/v1/super-admin/users/${id}/role`,
  USER_RESET_PW:     (id: string) => `/api/v1/super-admin/users/${id}/reset-password`,
  USER_IMPERSONATE:  (id: string) => `/api/v1/super-admin/users/${id}/impersonate`,
  USER_DELETE:       (id: string) => `/api/v1/super-admin/users/${id}`,
  USER_CREATE:       "/api/v1/super-admin/users/create",
  SUBSCRIPTIONS: "/api/v1/super-admin/subscriptions",
  PLANS:         "/api/v1/super-admin/plans",
} as const;
