// Full ISO 4217 list of active currencies — the single source of truth for
// every currency this app can display. `locale` drives number GROUPING (not
// the symbol) via toLocaleString — most currencies use standard 3-digit
// grouping (en-US), but a handful (INR, NPR, PKR — South Asian lakh/crore
// style) need their own locale to group correctly. Where no widely-used
// symbol exists, the ISO code itself is used as the display symbol, which is
// standard practice (e.g. "AWG 10.00").
export interface CurrencyDef {
  code: string;
  symbol: string;
  label: string;
  locale: string;
}

export const SUPPORTED_CURRENCIES: CurrencyDef[] = [
  { code: "AED", symbol: "د.إ", label: "UAE Dirham", locale: "en-US" },
  { code: "AFN", symbol: "؋", label: "Afghan Afghani", locale: "en-US" },
  { code: "ALL", symbol: "L", label: "Albanian Lek", locale: "en-US" },
  { code: "AMD", symbol: "֏", label: "Armenian Dram", locale: "en-US" },
  { code: "ANG", symbol: "ƒ", label: "Netherlands Antillean Guilder", locale: "en-US" },
  { code: "AOA", symbol: "Kz", label: "Angolan Kwanza", locale: "en-US" },
  { code: "ARS", symbol: "$", label: "Argentine Peso", locale: "en-US" },
  { code: "AUD", symbol: "$", label: "Australian Dollar", locale: "en-AU" },
  { code: "AWG", symbol: "ƒ", label: "Aruban Florin", locale: "en-US" },
  { code: "AZN", symbol: "₼", label: "Azerbaijani Manat", locale: "en-US" },
  { code: "BAM", symbol: "KM", label: "Bosnia-Herzegovina Convertible Mark", locale: "en-US" },
  { code: "BBD", symbol: "$", label: "Barbadian Dollar", locale: "en-US" },
  { code: "BDT", symbol: "৳", label: "Bangladeshi Taka", locale: "en-IN" },
  { code: "BGN", symbol: "лв", label: "Bulgarian Lev", locale: "en-US" },
  { code: "BHD", symbol: ".د.ب", label: "Bahraini Dinar", locale: "en-US" },
  { code: "BIF", symbol: "FBu", label: "Burundian Franc", locale: "en-US" },
  { code: "BMD", symbol: "$", label: "Bermudan Dollar", locale: "en-US" },
  { code: "BND", symbol: "$", label: "Brunei Dollar", locale: "en-US" },
  { code: "BOB", symbol: "Bs.", label: "Bolivian Boliviano", locale: "en-US" },
  { code: "BRL", symbol: "R$", label: "Brazilian Real", locale: "pt-BR" },
  { code: "BSD", symbol: "$", label: "Bahamian Dollar", locale: "en-US" },
  { code: "BTN", symbol: "Nu.", label: "Bhutanese Ngultrum", locale: "en-IN" },
  { code: "BWP", symbol: "P", label: "Botswanan Pula", locale: "en-US" },
  { code: "BYN", symbol: "Br", label: "Belarusian Ruble", locale: "en-US" },
  { code: "BZD", symbol: "$", label: "Belize Dollar", locale: "en-US" },
  { code: "CAD", symbol: "$", label: "Canadian Dollar", locale: "en-CA" },
  { code: "CDF", symbol: "FC", label: "Congolese Franc", locale: "en-US" },
  { code: "CHF", symbol: "CHF", label: "Swiss Franc", locale: "de-CH" },
  { code: "CLP", symbol: "$", label: "Chilean Peso", locale: "es-CL" },
  { code: "CNY", symbol: "¥", label: "Chinese Yuan", locale: "zh-CN" },
  { code: "COP", symbol: "$", label: "Colombian Peso", locale: "es-CO" },
  { code: "CRC", symbol: "₡", label: "Costa Rican Colón", locale: "en-US" },
  { code: "CUP", symbol: "$", label: "Cuban Peso", locale: "en-US" },
  { code: "CVE", symbol: "$", label: "Cape Verdean Escudo", locale: "en-US" },
  { code: "CZK", symbol: "Kč", label: "Czech Koruna", locale: "cs-CZ" },
  { code: "DJF", symbol: "Fdj", label: "Djiboutian Franc", locale: "en-US" },
  { code: "DKK", symbol: "kr", label: "Danish Krone", locale: "da-DK" },
  { code: "DOP", symbol: "RD$", label: "Dominican Peso", locale: "en-US" },
  { code: "DZD", symbol: "دج", label: "Algerian Dinar", locale: "en-US" },
  { code: "EGP", symbol: "£", label: "Egyptian Pound", locale: "en-US" },
  { code: "ERN", symbol: "Nfk", label: "Eritrean Nakfa", locale: "en-US" },
  { code: "ETB", symbol: "Br", label: "Ethiopian Birr", locale: "en-US" },
  { code: "EUR", symbol: "€", label: "Euro", locale: "de-DE" },
  { code: "FJD", symbol: "$", label: "Fijian Dollar", locale: "en-US" },
  { code: "FKP", symbol: "£", label: "Falkland Islands Pound", locale: "en-GB" },
  { code: "GBP", symbol: "£", label: "British Pound", locale: "en-GB" },
  { code: "GEL", symbol: "₾", label: "Georgian Lari", locale: "en-US" },
  { code: "GHS", symbol: "₵", label: "Ghanaian Cedi", locale: "en-US" },
  { code: "GIP", symbol: "£", label: "Gibraltar Pound", locale: "en-GB" },
  { code: "GMD", symbol: "D", label: "Gambian Dalasi", locale: "en-US" },
  { code: "GNF", symbol: "FG", label: "Guinean Franc", locale: "en-US" },
  { code: "GTQ", symbol: "Q", label: "Guatemalan Quetzal", locale: "en-US" },
  { code: "GYD", symbol: "$", label: "Guyanaese Dollar", locale: "en-US" },
  { code: "HKD", symbol: "$", label: "Hong Kong Dollar", locale: "en-HK" },
  { code: "HNL", symbol: "L", label: "Honduran Lempira", locale: "en-US" },
  { code: "HTG", symbol: "G", label: "Haitian Gourde", locale: "en-US" },
  { code: "HUF", symbol: "Ft", label: "Hungarian Forint", locale: "hu-HU" },
  { code: "IDR", symbol: "Rp", label: "Indonesian Rupiah", locale: "id-ID" },
  { code: "ILS", symbol: "₪", label: "Israeli New Shekel", locale: "en-US" },
  { code: "INR", symbol: "₹", label: "Indian Rupee", locale: "en-IN" },
  { code: "IQD", symbol: "ع.د", label: "Iraqi Dinar", locale: "en-US" },
  { code: "IRR", symbol: "﷼", label: "Iranian Rial", locale: "en-US" },
  { code: "ISK", symbol: "kr", label: "Icelandic Króna", locale: "is-IS" },
  { code: "JMD", symbol: "$", label: "Jamaican Dollar", locale: "en-US" },
  { code: "JOD", symbol: "د.ا", label: "Jordanian Dinar", locale: "en-US" },
  { code: "JPY", symbol: "¥", label: "Japanese Yen", locale: "ja-JP" },
  { code: "KES", symbol: "KSh", label: "Kenyan Shilling", locale: "en-US" },
  { code: "KGS", symbol: "лв", label: "Kyrgystani Som", locale: "en-US" },
  { code: "KHR", symbol: "៛", label: "Cambodian Riel", locale: "en-US" },
  { code: "KMF", symbol: "CF", label: "Comorian Franc", locale: "en-US" },
  { code: "KPW", symbol: "₩", label: "North Korean Won", locale: "en-US" },
  { code: "KRW", symbol: "₩", label: "South Korean Won", locale: "ko-KR" },
  { code: "KWD", symbol: "د.ك", label: "Kuwaiti Dinar", locale: "en-US" },
  { code: "KYD", symbol: "$", label: "Cayman Islands Dollar", locale: "en-US" },
  { code: "KZT", symbol: "₸", label: "Kazakhstani Tenge", locale: "en-US" },
  { code: "LAK", symbol: "₭", label: "Laotian Kip", locale: "en-US" },
  { code: "LBP", symbol: "ل.ل", label: "Lebanese Pound", locale: "en-US" },
  { code: "LKR", symbol: "₨", label: "Sri Lankan Rupee", locale: "en-IN" },
  { code: "LRD", symbol: "$", label: "Liberian Dollar", locale: "en-US" },
  { code: "LSL", symbol: "L", label: "Lesotho Loti", locale: "en-US" },
  { code: "LYD", symbol: "ل.د", label: "Libyan Dinar", locale: "en-US" },
  { code: "MAD", symbol: "د.م.", label: "Moroccan Dirham", locale: "en-US" },
  { code: "MDL", symbol: "L", label: "Moldovan Leu", locale: "en-US" },
  { code: "MGA", symbol: "Ar", label: "Malagasy Ariary", locale: "en-US" },
  { code: "MKD", symbol: "ден", label: "Macedonian Denar", locale: "en-US" },
  { code: "MMK", symbol: "K", label: "Myanmar Kyat", locale: "en-US" },
  { code: "MNT", symbol: "₮", label: "Mongolian Tugrik", locale: "en-US" },
  { code: "MOP", symbol: "MOP$", label: "Macanese Pataca", locale: "en-US" },
  { code: "MRU", symbol: "UM", label: "Mauritanian Ouguiya", locale: "en-US" },
  { code: "MUR", symbol: "₨", label: "Mauritian Rupee", locale: "en-US" },
  { code: "MVR", symbol: "Rf", label: "Maldivian Rufiyaa", locale: "en-US" },
  { code: "MWK", symbol: "MK", label: "Malawian Kwacha", locale: "en-US" },
  { code: "MXN", symbol: "$", label: "Mexican Peso", locale: "es-MX" },
  { code: "MYR", symbol: "RM", label: "Malaysian Ringgit", locale: "en-US" },
  { code: "MZN", symbol: "MT", label: "Mozambican Metical", locale: "en-US" },
  { code: "NAD", symbol: "$", label: "Namibian Dollar", locale: "en-US" },
  { code: "NGN", symbol: "₦", label: "Nigerian Naira", locale: "en-US" },
  { code: "NIO", symbol: "C$", label: "Nicaraguan Córdoba", locale: "en-US" },
  { code: "NOK", symbol: "kr", label: "Norwegian Krone", locale: "nb-NO" },
  { code: "NPR", symbol: "₨", label: "Nepalese Rupee", locale: "en-IN" },
  { code: "NZD", symbol: "$", label: "New Zealand Dollar", locale: "en-NZ" },
  { code: "OMR", symbol: "ر.ع.", label: "Omani Rial", locale: "en-US" },
  { code: "PAB", symbol: "B/.", label: "Panamanian Balboa", locale: "en-US" },
  { code: "PEN", symbol: "S/", label: "Peruvian Sol", locale: "en-US" },
  { code: "PGK", symbol: "K", label: "Papua New Guinean Kina", locale: "en-US" },
  { code: "PHP", symbol: "₱", label: "Philippine Peso", locale: "en-US" },
  { code: "PKR", symbol: "₨", label: "Pakistani Rupee", locale: "en-IN" },
  { code: "PLN", symbol: "zł", label: "Polish Złoty", locale: "pl-PL" },
  { code: "PYG", symbol: "₲", label: "Paraguayan Guarani", locale: "en-US" },
  { code: "QAR", symbol: "ر.ق", label: "Qatari Rial", locale: "en-US" },
  { code: "RON", symbol: "lei", label: "Romanian Leu", locale: "ro-RO" },
  { code: "RSD", symbol: "дин.", label: "Serbian Dinar", locale: "en-US" },
  { code: "RUB", symbol: "₽", label: "Russian Ruble", locale: "ru-RU" },
  { code: "RWF", symbol: "FRw", label: "Rwandan Franc", locale: "en-US" },
  { code: "SAR", symbol: "ر.س", label: "Saudi Riyal", locale: "en-US" },
  { code: "SBD", symbol: "$", label: "Solomon Islands Dollar", locale: "en-US" },
  { code: "SCR", symbol: "₨", label: "Seychellois Rupee", locale: "en-US" },
  { code: "SDG", symbol: "ج.س.", label: "Sudanese Pound", locale: "en-US" },
  { code: "SEK", symbol: "kr", label: "Swedish Krona", locale: "sv-SE" },
  { code: "SGD", symbol: "$", label: "Singapore Dollar", locale: "en-SG" },
  { code: "SHP", symbol: "£", label: "Saint Helena Pound", locale: "en-GB" },
  { code: "SLE", symbol: "Le", label: "Sierra Leonean Leone", locale: "en-US" },
  { code: "SOS", symbol: "S", label: "Somali Shilling", locale: "en-US" },
  { code: "SRD", symbol: "$", label: "Surinamese Dollar", locale: "en-US" },
  { code: "SSP", symbol: "£", label: "South Sudanese Pound", locale: "en-US" },
  { code: "STN", symbol: "Db", label: "São Tomé & Príncipe Dobra", locale: "en-US" },
  { code: "SYP", symbol: "£", label: "Syrian Pound", locale: "en-US" },
  { code: "SZL", symbol: "L", label: "Swazi Lilangeni", locale: "en-US" },
  { code: "THB", symbol: "฿", label: "Thai Baht", locale: "th-TH" },
  { code: "TJS", symbol: "SM", label: "Tajikistani Somoni", locale: "en-US" },
  { code: "TMT", symbol: "m", label: "Turkmenistani Manat", locale: "en-US" },
  { code: "TND", symbol: "د.ت", label: "Tunisian Dinar", locale: "en-US" },
  { code: "TOP", symbol: "T$", label: "Tongan Paʻanga", locale: "en-US" },
  { code: "TRY", symbol: "₺", label: "Turkish Lira", locale: "tr-TR" },
  { code: "TTD", symbol: "$", label: "Trinidad & Tobago Dollar", locale: "en-US" },
  { code: "TWD", symbol: "NT$", label: "New Taiwan Dollar", locale: "en-US" },
  { code: "TZS", symbol: "TSh", label: "Tanzanian Shilling", locale: "en-US" },
  { code: "UAH", symbol: "₴", label: "Ukrainian Hryvnia", locale: "uk-UA" },
  { code: "UGX", symbol: "USh", label: "Ugandan Shilling", locale: "en-US" },
  { code: "USD", symbol: "$", label: "US Dollar", locale: "en-US" },
  { code: "UYU", symbol: "$U", label: "Uruguayan Peso", locale: "en-US" },
  { code: "UZS", symbol: "лв", label: "Uzbekistani Som", locale: "en-US" },
  { code: "VES", symbol: "Bs.", label: "Venezuelan Bolívar", locale: "en-US" },
  { code: "VND", symbol: "₫", label: "Vietnamese Dong", locale: "vi-VN" },
  { code: "VUV", symbol: "VT", label: "Vanuatu Vatu", locale: "en-US" },
  { code: "WST", symbol: "WS$", label: "Samoan Tala", locale: "en-US" },
  { code: "XAF", symbol: "FCFA", label: "Central African CFA Franc", locale: "en-US" },
  { code: "XCD", symbol: "$", label: "East Caribbean Dollar", locale: "en-US" },
  { code: "XOF", symbol: "CFA", label: "West African CFA Franc", locale: "en-US" },
  { code: "XPF", symbol: "₣", label: "CFP Franc", locale: "en-US" },
  { code: "YER", symbol: "﷼", label: "Yemeni Rial", locale: "en-US" },
  { code: "ZAR", symbol: "R", label: "South African Rand", locale: "en-ZA" },
  { code: "ZMW", symbol: "ZK", label: "Zambian Kwacha", locale: "en-US" },
  { code: "ZWL", symbol: "$", label: "Zimbabwean Dollar", locale: "en-US" },
];

export const DEFAULT_CURRENCY_CODE = "INR";

export function getCurrencyDef(code: string | null | undefined): CurrencyDef {
  return (
    SUPPORTED_CURRENCIES.find((c) => c.code === code) ??
    SUPPORTED_CURRENCIES.find((c) => c.code === DEFAULT_CURRENCY_CODE)!
  );
}
