import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDateDDMMYYYY } from "../../../utils/dateFormat";

export interface PDFExportOptions {
  salon?: {
    business_name?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    phone?: string | null;
    gst_number?: string | null;
    currency?: string | null;
  } | null;
  user?: {
    fullName?: string | null;
  } | null;
}

// jsPDF's built-in Helvetica cannot render ₹ (U+20B9).
const sanitize = (v: string) => v.replace(/₹/g, "Rs.");
const d = (v: unknown) => (v == null || v === "" ? "—" : sanitize(String(v)));

const formatDateISO = (date: Date) => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
};

const formatDisplayDate = (date: Date) => formatDateDDMMYYYY(date);

const formatGeneratedDateTime = (date: Date) => {
  const timeStr = date.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true });
  return `${formatDisplayDate(date)}, ${timeStr}`;
};

const formatPricePDF = (price: unknown, sym = "Rs.") => {
  if (price == null || price === "") return "—";
  const num = typeof price === "number" ? price : parseFloat(String(price));
  if (isNaN(num)) return String(price);
  const formatted = num.toFixed(num % 1 === 0 ? 0 : 2)
    .replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `${sym}${formatted}`;
};

const formatGST = (p: any) => {
  // Use tax_type if custom_tax_rate is not set, or tax_rate if present
  let gstStr = p.tax_type ?? p.gst ?? p.tax_rate;
  if (gstStr === "no_tax") return "—";
  if (gstStr === "custom") return p.custom_tax_rate != null ? `${p.custom_tax_rate}%` : "—";
  if (typeof gstStr === "string" && gstStr.startsWith("gst_")) {
    return `${gstStr.replace("gst_", "")}%`;
  }
  if (gstStr != null && gstStr !== "") {
    const num = parseFloat(String(gstStr));
    return isNaN(num) ? String(gstStr) : `${num}%`;
  }
  return "—";
};

// # | Product Name | Barcode | Brand | Supplier | Type | Measure | Supply Price | Retail Price | GST | Stock | Status
export const exportProductsPDF = (
  products: any[],
  supplierMap: Record<string, string>,
  brandMap: Record<string, string>,
  options: PDFExportOptions = {}
) => {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth  = doc.internal.pageSize.getWidth();   // 297
  const pageHeight = doc.internal.pageSize.getHeight();  // 210
  const margin     = 14;
  const contentW   = pageWidth - margin * 2;             // 269

  const salonName   = options.salon?.business_name || "Salon";
  const userName    = options.user?.fullName || "Admin";
  const generatedAt = new Date();
  const dateStr     = formatGeneratedDateTime(generatedAt);
  const currencySym = options.salon?.currency === "USD" ? "$" : "Rs.";

  const addrParts  = [options.salon?.address, options.salon?.city, options.salon?.state].filter(Boolean);
  const addressStr = addrParts.join(", ");
  const phoneStr   = options.salon?.phone   ? `Phone: ${options.salon.phone}` : "";
  const gstStr     = options.salon?.gst_number ? `GSTIN: ${options.salon.gst_number}` : "";
  const contactLine = [phoneStr, gstStr].filter(Boolean).join("   |   ");

  // Colour palette
  const PRIMARY  : [number,number,number] = [30, 27, 75];
  const ACCENT   : [number,number,number] = [79, 70, 229];
  const TEXT     : [number,number,number] = [17, 24, 39];
  const GRAY     : [number,number,number] = [100, 116, 139];
  const CARD_BG  : [number,number,number] = [248, 250, 252];
  const BORDER   : [number,number,number] = [226, 232, 240];
  const WHITE    : [number,number,number] = [255, 255, 255];

  const drawFooter = (pageNum: number, pageTotal: number) => {
    doc.setPage(pageNum);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(`Generated by ${salonName}`, margin, pageHeight - 9);
    doc.text(`Page ${pageNum} of ${pageTotal}`, pageWidth - margin, pageHeight - 9, { align: "right" });
  };

  // 1. PAGE HEADER
  let curY = 14;

  // Left – salon name + contact
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...PRIMARY);
  doc.text(salonName, margin, curY + 5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...GRAY);
  let subY = curY + 10.5;
  if (addressStr) { doc.text(addressStr, margin, subY); subY += 4.5; }
  if (contactLine) { doc.text(contactLine, margin, subY); subY += 4.5; }

  // Right – catalog title + meta
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...ACCENT);
  doc.text("Product Catalog", pageWidth - margin, curY + 5, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...GRAY);
  doc.text(`Generated On: ${dateStr}`, pageWidth - margin, curY + 10.5, { align: "right" });
  doc.text(`Generated By: ${userName}`,  pageWidth - margin, curY + 15,   { align: "right" });

  curY = Math.max(subY, curY + 19) + 3;

  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.4);
  doc.line(margin, curY, pageWidth - margin, curY);
  curY += 6;

  // 2. KPI SUMMARY CARDS
  const totalProducts = products.length;
  const activeProducts = products.filter((p) => p.is_active).length;
  const inactiveProducts = totalProducts - activeProducts;
  const uniqueCats = new Set(products.map((p) => p.category_id || "Uncategorised")).size;

  const kpis = [
    { label: "TOTAL PRODUCTS",    value: String(totalProducts) },
    { label: "ACTIVE PRODUCTS",   value: String(activeProducts) },
    { label: "INACTIVE PRODUCTS", value: String(inactiveProducts) },
    { label: "CATEGORIES",        value: String(uniqueCats) },
  ];

  const gap       = 3.5;
  const cardW     = (contentW - gap * 3) / 4;
  const cardH     = 16;

  kpis.forEach((kpi, idx) => {
    const x = margin + idx * (cardW + gap);
    doc.setFillColor(...CARD_BG);
    doc.setDrawColor(...BORDER);
    doc.roundedRect(x, curY, cardW, cardH, 1.5, 1.5, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(...GRAY);
    doc.text(kpi.label, x + 3.5, curY + 5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...TEXT);
    doc.text(kpi.value, x + 3.5, curY + 12.5);
  });

  curY += cardH + 8;

  // 3. SUMMARY TABLE
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...PRIMARY);
  doc.text("Product Summary", margin, curY);
  curY += 5;

  autoTable(doc, {
    head: [["#", "Product Name", "Barcode", "Brand", "Supplier", "Type", "Measure", "Supply Price", "Retail Price", "GST", "Stock", "Status"]],
    body: products.map((p, i) => {
      const typeMap: Record<string, string> = { retail: "Retail", consumable: "Consumable", both: "Both" };
      
      const bottleSize = parseFloat(p.bottle_size);
      const measure = (!isNaN(bottleSize) && bottleSize > 0) ? `${bottleSize} ${p.measure_unit ?? ""}`.trim() : (p.size || "—");
      
      const rawAmount = parseFloat(p.amount);
      const amount = isNaN(rawAmount) ? 0 : rawAmount;
      const stock = (!isNaN(bottleSize) && bottleSize > 0) ? Math.ceil(amount / bottleSize) : amount;

      return [
        String(i + 1),
        d(p.name),
        d(p.barcode),
        d(p.brand_id ? brandMap[p.brand_id] ?? p.brand_id : ""),
        d(p.supplier_id ? supplierMap[p.supplier_id] ?? p.supplier_id : ""),
        typeMap[p.product_type || "retail"] ?? "Retail",
        d(measure),
        formatPricePDF(p.supply_price, currencySym),
        formatPricePDF(p.retail_price, currencySym),
        formatGST(p),
        String(stock),
        p.is_active ? "Active" : "Inactive",
      ];
    }),
    startY: curY,
    margin: { left: margin, right: margin, bottom: 18 },
    styles: {
      fontSize: 8.5,
      cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
      overflow: "linebreak",
      textColor: TEXT,
      lineColor: BORDER,
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: PRIMARY,
      textColor: WHITE,
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: { fillColor: CARD_BG },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 38, fontStyle: "bold" },
      2: { cellWidth: 20 },
      3: { cellWidth: 24 },
      4: { cellWidth: 24 },
      5: { cellWidth: 20, halign: "center" },
      6: { cellWidth: 18, halign: "center" },
      7: { cellWidth: 26, halign: "right" },
      8: { cellWidth: 26, halign: "right", fontStyle: "bold" },
      9: { cellWidth: 15, halign: "center" },
      10: { cellWidth: 18, halign: "center" },
      11: { cellWidth: 18, halign: "center" },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 11) {
        data.cell.styles.textColor = data.cell.raw === "Active" ? [22, 163, 74] : [220, 38, 38];
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) drawFooter(p, pageCount);

  doc.save(`Products_Catalog_${formatDateISO(generatedAt)}.pdf`);
};
