export interface CountryOption {
  name: string;
  dialCode: string;
  cca2: string;
  flag: string;
}

function flag(cca2: string): string {
  return [...cca2.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join("");
}

const raw: [string, string, string][] = [
  ["Afghanistan", "+93", "AF"],
  ["Albania", "+355", "AL"],
  ["Algeria", "+213", "DZ"],
  ["Angola", "+244", "AO"],
  ["Argentina", "+54", "AR"],
  ["Armenia", "+374", "AM"],
  ["Australia", "+61", "AU"],
  ["Austria", "+43", "AT"],
  ["Azerbaijan", "+994", "AZ"],
  ["Bahrain", "+973", "BH"],
  ["Bangladesh", "+880", "BD"],
  ["Belarus", "+375", "BY"],
  ["Belgium", "+32", "BE"],
  ["Bolivia", "+591", "BO"],
  ["Bosnia and Herzegovina", "+387", "BA"],
  ["Brazil", "+55", "BR"],
  ["Bulgaria", "+359", "BG"],
  ["Cambodia", "+855", "KH"],
  ["Cameroon", "+237", "CM"],
  ["Canada", "+1", "CA"],
  ["Chile", "+56", "CL"],
  ["China", "+86", "CN"],
  ["Colombia", "+57", "CO"],
  ["Croatia", "+385", "HR"],
  ["Cuba", "+53", "CU"],
  ["Cyprus", "+357", "CY"],
  ["Czech Republic", "+420", "CZ"],
  ["Denmark", "+45", "DK"],
  ["Ecuador", "+593", "EC"],
  ["Egypt", "+20", "EG"],
  ["Estonia", "+372", "EE"],
  ["Ethiopia", "+251", "ET"],
  ["Finland", "+358", "FI"],
  ["France", "+33", "FR"],
  ["Georgia", "+995", "GE"],
  ["Germany", "+49", "DE"],
  ["Ghana", "+233", "GH"],
  ["Greece", "+30", "GR"],
  ["Guatemala", "+502", "GT"],
  ["Hong Kong", "+852", "HK"],
  ["Hungary", "+36", "HU"],
  ["Iceland", "+354", "IS"],
  ["India", "+91", "IN"],
  ["Indonesia", "+62", "ID"],
  ["Iran", "+98", "IR"],
  ["Iraq", "+964", "IQ"],
  ["Ireland", "+353", "IE"],
  ["Israel", "+972", "IL"],
  ["Italy", "+39", "IT"],
  ["Japan", "+81", "JP"],
  ["Jordan", "+962", "JO"],
  ["Kazakhstan", "+7", "KZ"],
  ["Kenya", "+254", "KE"],
  ["Kuwait", "+965", "KW"],
  ["Kyrgyzstan", "+996", "KG"],
  ["Latvia", "+371", "LV"],
  ["Lebanon", "+961", "LB"],
  ["Libya", "+218", "LY"],
  ["Lithuania", "+370", "LT"],
  ["Luxembourg", "+352", "LU"],
  ["Malaysia", "+60", "MY"],
  ["Maldives", "+960", "MV"],
  ["Mexico", "+52", "MX"],
  ["Moldova", "+373", "MD"],
  ["Mongolia", "+976", "MN"],
  ["Morocco", "+212", "MA"],
  ["Mozambique", "+258", "MZ"],
  ["Myanmar", "+95", "MM"],
  ["Nepal", "+977", "NP"],
  ["Netherlands", "+31", "NL"],
  ["New Zealand", "+64", "NZ"],
  ["Nigeria", "+234", "NG"],
  ["Norway", "+47", "NO"],
  ["Oman", "+968", "OM"],
  ["Pakistan", "+92", "PK"],
  ["Palestine", "+970", "PS"],
  ["Panama", "+507", "PA"],
  ["Peru", "+51", "PE"],
  ["Philippines", "+63", "PH"],
  ["Poland", "+48", "PL"],
  ["Portugal", "+351", "PT"],
  ["Qatar", "+974", "QA"],
  ["Romania", "+40", "RO"],
  ["Russia", "+7", "RU"],
  ["Saudi Arabia", "+966", "SA"],
  ["Serbia", "+381", "RS"],
  ["Singapore", "+65", "SG"],
  ["Slovakia", "+421", "SK"],
  ["Slovenia", "+386", "SI"],
  ["Somalia", "+252", "SO"],
  ["South Africa", "+27", "ZA"],
  ["South Korea", "+82", "KR"],
  ["Spain", "+34", "ES"],
  ["Sri Lanka", "+94", "LK"],
  ["Sudan", "+249", "SD"],
  ["Sweden", "+46", "SE"],
  ["Switzerland", "+41", "CH"],
  ["Syria", "+963", "SY"],
  ["Taiwan", "+886", "TW"],
  ["Tajikistan", "+992", "TJ"],
  ["Tanzania", "+255", "TZ"],
  ["Thailand", "+66", "TH"],
  ["Tunisia", "+216", "TN"],
  ["Turkey", "+90", "TR"],
  ["Turkmenistan", "+993", "TM"],
  ["Uganda", "+256", "UG"],
  ["Ukraine", "+380", "UA"],
  ["United Arab Emirates", "+971", "AE"],
  ["United Kingdom", "+44", "GB"],
  ["United States", "+1", "US"],
  ["Uruguay", "+598", "UY"],
  ["Uzbekistan", "+998", "UZ"],
  ["Venezuela", "+58", "VE"],
  ["Vietnam", "+84", "VN"],
  ["Yemen", "+967", "YE"],
  ["Zambia", "+260", "ZM"],
  ["Zimbabwe", "+263", "ZW"],
];

export const COUNTRIES: CountryOption[] = raw
  .map(([name, dialCode, cca2]) => ({ name, dialCode, cca2, flag: flag(cca2) }))
  .sort((a, b) => a.name.localeCompare(b.name));
